// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: youtube_output.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

// SPDX-FileCopyrightText: 2026 Kaito Udagawa <umireon@kaito.tokyo>
//
// SPDX-License-Identifier: Apache-2.0

#if canImport(FoundationEssentials)
import FoundationEssentials
#else
import Foundation
#endif
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public nonisolated enum Ldtx_YoutubeOutput_V1_PCMSampleFormat: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case unspecified // = 0
  case float32Interleaved // = 1
  case UNRECOGNIZED(Int)

  public init() {
    self = .unspecified
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .float32Interleaved
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .float32Interleaved: return 1
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [Ldtx_YoutubeOutput_V1_PCMSampleFormat] = [
    .unspecified,
    .float32Interleaved,
  ]

}

public nonisolated struct Ldtx_YoutubeOutput_V1_Context: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var sessionID: String = String()

  public var generation: UInt64 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public nonisolated struct Ldtx_YoutubeOutput_V1_Representation: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var id: String = String()

  public var bandwidth: Int32 = 0

  public var width: Int32 = 0

  public var height: Int32 = 0

  public var frameRate: String = String()

  public var codecs: String = String()

  public var audioSamplingRate: Int32 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public nonisolated struct Ldtx_YoutubeOutput_V1_Bootstrap: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var protocolVersion: UInt32 {
    get {_storage._protocolVersion}
    set {_uniqueStorage()._protocolVersion = newValue}
  }

  public var context: Ldtx_YoutubeOutput_V1_Context {
    get {_storage._context ?? Ldtx_YoutubeOutput_V1_Context()}
    set {_uniqueStorage()._context = newValue}
  }
  /// Returns true if `context` has been explicitly set.
  public var hasContext: Bool {_storage._context != nil}
  /// Clears the value of `context`. Subsequent reads from it will return its default value.
  public mutating func clearContext() {_uniqueStorage()._context = nil}

  public var endpoint: String {
    get {_storage._endpoint}
    set {_uniqueStorage()._endpoint = newValue}
  }

  public var availabilityStartTimeMilliseconds: Int64 {
    get {_storage._availabilityStartTimeMilliseconds}
    set {_uniqueStorage()._availabilityStartTimeMilliseconds = newValue}
  }

  public var timescale: Int32 {
    get {_storage._timescale}
    set {_uniqueStorage()._timescale = newValue}
  }

  public var segmentDurationSeconds: Int32 {
    get {_storage._segmentDurationSeconds}
    set {_uniqueStorage()._segmentDurationSeconds = newValue}
  }

  public var startNumber: Int32 {
    get {_storage._startNumber}
    set {_uniqueStorage()._startNumber = newValue}
  }

  public var mediaTemplate: String {
    get {_storage._mediaTemplate}
    set {_uniqueStorage()._mediaTemplate = newValue}
  }

  public var representation: Ldtx_YoutubeOutput_V1_Representation {
    get {_storage._representation ?? Ldtx_YoutubeOutput_V1_Representation()}
    set {_uniqueStorage()._representation = newValue}
  }
  /// Returns true if `representation` has been explicitly set.
  public var hasRepresentation: Bool {_storage._representation != nil}
  /// Clears the value of `representation`. Subsequent reads from it will return its default value.
  public mutating func clearRepresentation() {_uniqueStorage()._representation = nil}

  public var configurationFingerprint: String {
    get {_storage._configurationFingerprint}
    set {_uniqueStorage()._configurationFingerprint = newValue}
  }

  public var initializationSegment: Data {
    get {_storage._initializationSegment ?? Data()}
    set {_uniqueStorage()._initializationSegment = newValue}
  }
  /// Returns true if `initializationSegment` has been explicitly set.
  public var hasInitializationSegment: Bool {_storage._initializationSegment != nil}
  /// Clears the value of `initializationSegment`. Subsequent reads from it will return its default value.
  public mutating func clearInitializationSegment() {_uniqueStorage()._initializationSegment = nil}

  public var persistenceIdentifier: String {
    get {_storage._persistenceIdentifier}
    set {_uniqueStorage()._persistenceIdentifier = newValue}
  }

  public var nextMediaTimeSeconds: Double {
    get {_storage._nextMediaTimeSeconds ?? 0}
    set {_uniqueStorage()._nextMediaTimeSeconds = newValue}
  }
  /// Returns true if `nextMediaTimeSeconds` has been explicitly set.
  public var hasNextMediaTimeSeconds: Bool {_storage._nextMediaTimeSeconds != nil}
  /// Clears the value of `nextMediaTimeSeconds`. Subsequent reads from it will return its default value.
  public mutating func clearNextMediaTimeSeconds() {_uniqueStorage()._nextMediaTimeSeconds = nil}

  public var sharedVideoSlotCount: Int32 {
    get {_storage._sharedVideoSlotCount}
    set {_uniqueStorage()._sharedVideoSlotCount = newValue}
  }

  public var sharedVideoSlotSize: Int32 {
    get {_storage._sharedVideoSlotSize}
    set {_uniqueStorage()._sharedVideoSlotSize = newValue}
  }

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

public nonisolated struct Ldtx_YoutubeOutput_V1_SharedMemorySlice: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var slot: Int32 = 0

  public var generation: UInt64 = 0

  public var offset: Int32 = 0

  public var length: Int32 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public nonisolated struct Ldtx_YoutubeOutput_V1_FinishRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var context: Ldtx_YoutubeOutput_V1_Context {
    get {_context ?? Ldtx_YoutubeOutput_V1_Context()}
    set {_context = newValue}
  }
  /// Returns true if `context` has been explicitly set.
  public var hasContext: Bool {self._context != nil}
  /// Clears the value of `context`. Subsequent reads from it will return its default value.
  public mutating func clearContext() {self._context = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _context: Ldtx_YoutubeOutput_V1_Context? = nil
}

public nonisolated struct Ldtx_YoutubeOutput_V1_Reply: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var context: Ldtx_YoutubeOutput_V1_Context {
    get {_context ?? Ldtx_YoutubeOutput_V1_Context()}
    set {_context = newValue}
  }
  /// Returns true if `context` has been explicitly set.
  public var hasContext: Bool {self._context != nil}
  /// Clears the value of `context`. Subsequent reads from it will return its default value.
  public mutating func clearContext() {self._context = nil}

  public var sequence: UInt64 {
    get {_sequence ?? 0}
    set {_sequence = newValue}
  }
  /// Returns true if `sequence` has been explicitly set.
  public var hasSequence: Bool {self._sequence != nil}
  /// Clears the value of `sequence`. Subsequent reads from it will return its default value.
  public mutating func clearSequence() {self._sequence = nil}

  public var nextMediaSegmentNumber: Int32 {
    get {_nextMediaSegmentNumber ?? 0}
    set {_nextMediaSegmentNumber = newValue}
  }
  /// Returns true if `nextMediaSegmentNumber` has been explicitly set.
  public var hasNextMediaSegmentNumber: Bool {self._nextMediaSegmentNumber != nil}
  /// Clears the value of `nextMediaSegmentNumber`. Subsequent reads from it will return its default value.
  public mutating func clearNextMediaSegmentNumber() {self._nextMediaSegmentNumber = nil}

  public var initializationSegment: Data {
    get {_initializationSegment ?? Data()}
    set {_initializationSegment = newValue}
  }
  /// Returns true if `initializationSegment` has been explicitly set.
  public var hasInitializationSegment: Bool {self._initializationSegment != nil}
  /// Clears the value of `initializationSegment`. Subsequent reads from it will return its default value.
  public mutating func clearInitializationSegment() {self._initializationSegment = nil}

  public var configurationFingerprint: String {
    get {_configurationFingerprint ?? String()}
    set {_configurationFingerprint = newValue}
  }
  /// Returns true if `configurationFingerprint` has been explicitly set.
  public var hasConfigurationFingerprint: Bool {self._configurationFingerprint != nil}
  /// Clears the value of `configurationFingerprint`. Subsequent reads from it will return its default value.
  public mutating func clearConfigurationFingerprint() {self._configurationFingerprint = nil}

  public var eventDescription: String {
    get {_eventDescription ?? String()}
    set {_eventDescription = newValue}
  }
  /// Returns true if `eventDescription` has been explicitly set.
  public var hasEventDescription: Bool {self._eventDescription != nil}
  /// Clears the value of `eventDescription`. Subsequent reads from it will return its default value.
  public mutating func clearEventDescription() {self._eventDescription = nil}

  public var errorDescription: String {
    get {_errorDescription ?? String()}
    set {_errorDescription = newValue}
  }
  /// Returns true if `errorDescription` has been explicitly set.
  public var hasErrorDescription: Bool {self._errorDescription != nil}
  /// Clears the value of `errorDescription`. Subsequent reads from it will return its default value.
  public mutating func clearErrorDescription() {self._errorDescription = nil}

  public var availabilityStartTimeMilliseconds: Int64 {
    get {_availabilityStartTimeMilliseconds ?? 0}
    set {_availabilityStartTimeMilliseconds = newValue}
  }
  /// Returns true if `availabilityStartTimeMilliseconds` has been explicitly set.
  public var hasAvailabilityStartTimeMilliseconds: Bool {self._availabilityStartTimeMilliseconds != nil}
  /// Clears the value of `availabilityStartTimeMilliseconds`. Subsequent reads from it will return its default value.
  public mutating func clearAvailabilityStartTimeMilliseconds() {self._availabilityStartTimeMilliseconds = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _context: Ldtx_YoutubeOutput_V1_Context? = nil
  fileprivate var _sequence: UInt64? = nil
  fileprivate var _nextMediaSegmentNumber: Int32? = nil
  fileprivate var _initializationSegment: Data? = nil
  fileprivate var _configurationFingerprint: String? = nil
  fileprivate var _eventDescription: String? = nil
  fileprivate var _errorDescription: String? = nil
  fileprivate var _availabilityStartTimeMilliseconds: Int64? = nil
}

public nonisolated struct Ldtx_YoutubeOutput_V1_ResetRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var context: Ldtx_YoutubeOutput_V1_Context {
    get {_context ?? Ldtx_YoutubeOutput_V1_Context()}
    set {_context = newValue}
  }
  /// Returns true if `context` has been explicitly set.
  public var hasContext: Bool {self._context != nil}
  /// Clears the value of `context`. Subsequent reads from it will return its default value.
  public mutating func clearContext() {self._context = nil}

  public var reason: String = String()

  public var nextMediaSegmentNumber: Int32 {
    get {_nextMediaSegmentNumber ?? 0}
    set {_nextMediaSegmentNumber = newValue}
  }
  /// Returns true if `nextMediaSegmentNumber` has been explicitly set.
  public var hasNextMediaSegmentNumber: Bool {self._nextMediaSegmentNumber != nil}
  /// Clears the value of `nextMediaSegmentNumber`. Subsequent reads from it will return its default value.
  public mutating func clearNextMediaSegmentNumber() {self._nextMediaSegmentNumber = nil}

  public var initializationSegment: Data {
    get {_initializationSegment ?? Data()}
    set {_initializationSegment = newValue}
  }
  /// Returns true if `initializationSegment` has been explicitly set.
  public var hasInitializationSegment: Bool {self._initializationSegment != nil}
  /// Clears the value of `initializationSegment`. Subsequent reads from it will return its default value.
  public mutating func clearInitializationSegment() {self._initializationSegment = nil}

  public var configurationFingerprint: String {
    get {_configurationFingerprint ?? String()}
    set {_configurationFingerprint = newValue}
  }
  /// Returns true if `configurationFingerprint` has been explicitly set.
  public var hasConfigurationFingerprint: Bool {self._configurationFingerprint != nil}
  /// Clears the value of `configurationFingerprint`. Subsequent reads from it will return its default value.
  public mutating func clearConfigurationFingerprint() {self._configurationFingerprint = nil}

  public var availabilityStartTimeMilliseconds: Int64 {
    get {_availabilityStartTimeMilliseconds ?? 0}
    set {_availabilityStartTimeMilliseconds = newValue}
  }
  /// Returns true if `availabilityStartTimeMilliseconds` has been explicitly set.
  public var hasAvailabilityStartTimeMilliseconds: Bool {self._availabilityStartTimeMilliseconds != nil}
  /// Clears the value of `availabilityStartTimeMilliseconds`. Subsequent reads from it will return its default value.
  public mutating func clearAvailabilityStartTimeMilliseconds() {self._availabilityStartTimeMilliseconds = nil}

  public var nextMediaTimeSeconds: Double {
    get {_nextMediaTimeSeconds ?? 0}
    set {_nextMediaTimeSeconds = newValue}
  }
  /// Returns true if `nextMediaTimeSeconds` has been explicitly set.
  public var hasNextMediaTimeSeconds: Bool {self._nextMediaTimeSeconds != nil}
  /// Clears the value of `nextMediaTimeSeconds`. Subsequent reads from it will return its default value.
  public mutating func clearNextMediaTimeSeconds() {self._nextMediaTimeSeconds = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _context: Ldtx_YoutubeOutput_V1_Context? = nil
  fileprivate var _nextMediaSegmentNumber: Int32? = nil
  fileprivate var _initializationSegment: Data? = nil
  fileprivate var _configurationFingerprint: String? = nil
  fileprivate var _availabilityStartTimeMilliseconds: Int64? = nil
  fileprivate var _nextMediaTimeSeconds: Double? = nil
}

public nonisolated struct Ldtx_YoutubeOutput_V1_MediaTime: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var value: Int64 = 0

  public var timescale: Int32 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public nonisolated struct Ldtx_YoutubeOutput_V1_H264Format: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var parameterSets: [Data] = []

  public var nalUnitHeaderLength: Int32 = 0

  public var width: Int32 = 0

  public var height: Int32 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public nonisolated struct Ldtx_YoutubeOutput_V1_H264AccessUnit: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var presentationTime: Ldtx_YoutubeOutput_V1_MediaTime {
    get {_presentationTime ?? Ldtx_YoutubeOutput_V1_MediaTime()}
    set {_presentationTime = newValue}
  }
  /// Returns true if `presentationTime` has been explicitly set.
  public var hasPresentationTime: Bool {self._presentationTime != nil}
  /// Clears the value of `presentationTime`. Subsequent reads from it will return its default value.
  public mutating func clearPresentationTime() {self._presentationTime = nil}

  public var decodeTime: Ldtx_YoutubeOutput_V1_MediaTime {
    get {_decodeTime ?? Ldtx_YoutubeOutput_V1_MediaTime()}
    set {_decodeTime = newValue}
  }
  /// Returns true if `decodeTime` has been explicitly set.
  public var hasDecodeTime: Bool {self._decodeTime != nil}
  /// Clears the value of `decodeTime`. Subsequent reads from it will return its default value.
  public mutating func clearDecodeTime() {self._decodeTime = nil}

  public var duration: Ldtx_YoutubeOutput_V1_MediaTime {
    get {_duration ?? Ldtx_YoutubeOutput_V1_MediaTime()}
    set {_duration = newValue}
  }
  /// Returns true if `duration` has been explicitly set.
  public var hasDuration: Bool {self._duration != nil}
  /// Clears the value of `duration`. Subsequent reads from it will return its default value.
  public mutating func clearDuration() {self._duration = nil}

  public var keyFrame: Bool = false

  public var avccData: Data = Data()

  public var sharedMemory: Ldtx_YoutubeOutput_V1_SharedMemorySlice {
    get {_sharedMemory ?? Ldtx_YoutubeOutput_V1_SharedMemorySlice()}
    set {_sharedMemory = newValue}
  }
  /// Returns true if `sharedMemory` has been explicitly set.
  public var hasSharedMemory: Bool {self._sharedMemory != nil}
  /// Clears the value of `sharedMemory`. Subsequent reads from it will return its default value.
  public mutating func clearSharedMemory() {self._sharedMemory = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _presentationTime: Ldtx_YoutubeOutput_V1_MediaTime? = nil
  fileprivate var _decodeTime: Ldtx_YoutubeOutput_V1_MediaTime? = nil
  fileprivate var _duration: Ldtx_YoutubeOutput_V1_MediaTime? = nil
  fileprivate var _sharedMemory: Ldtx_YoutubeOutput_V1_SharedMemorySlice? = nil
}

public nonisolated struct Ldtx_YoutubeOutput_V1_PCMBuffer: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var presentationTime: Ldtx_YoutubeOutput_V1_MediaTime {
    get {_presentationTime ?? Ldtx_YoutubeOutput_V1_MediaTime()}
    set {_presentationTime = newValue}
  }
  /// Returns true if `presentationTime` has been explicitly set.
  public var hasPresentationTime: Bool {self._presentationTime != nil}
  /// Clears the value of `presentationTime`. Subsequent reads from it will return its default value.
  public mutating func clearPresentationTime() {self._presentationTime = nil}

  public var duration: Ldtx_YoutubeOutput_V1_MediaTime {
    get {_duration ?? Ldtx_YoutubeOutput_V1_MediaTime()}
    set {_duration = newValue}
  }
  /// Returns true if `duration` has been explicitly set.
  public var hasDuration: Bool {self._duration != nil}
  /// Clears the value of `duration`. Subsequent reads from it will return its default value.
  public mutating func clearDuration() {self._duration = nil}

  public var sampleRate: Int32 = 0

  public var channelCount: Int32 = 0

  public var frameCount: Int32 = 0

  public var sampleFormat: Ldtx_YoutubeOutput_V1_PCMSampleFormat = .unspecified

  public var data: Data = Data()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _presentationTime: Ldtx_YoutubeOutput_V1_MediaTime? = nil
  fileprivate var _duration: Ldtx_YoutubeOutput_V1_MediaTime? = nil
}

public nonisolated struct Ldtx_YoutubeOutput_V1_MediaBatch: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var protocolVersion: UInt32 = 0

  public var context: Ldtx_YoutubeOutput_V1_Context {
    get {_context ?? Ldtx_YoutubeOutput_V1_Context()}
    set {_context = newValue}
  }
  /// Returns true if `context` has been explicitly set.
  public var hasContext: Bool {self._context != nil}
  /// Clears the value of `context`. Subsequent reads from it will return its default value.
  public mutating func clearContext() {self._context = nil}

  public var sequence: UInt64 = 0

  public var videoFormat: Ldtx_YoutubeOutput_V1_H264Format {
    get {_videoFormat ?? Ldtx_YoutubeOutput_V1_H264Format()}
    set {_videoFormat = newValue}
  }
  /// Returns true if `videoFormat` has been explicitly set.
  public var hasVideoFormat: Bool {self._videoFormat != nil}
  /// Clears the value of `videoFormat`. Subsequent reads from it will return its default value.
  public mutating func clearVideoFormat() {self._videoFormat = nil}

  public var video: [Ldtx_YoutubeOutput_V1_H264AccessUnit] = []

  public var audio: [Ldtx_YoutubeOutput_V1_PCMBuffer] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _context: Ldtx_YoutubeOutput_V1_Context? = nil
  fileprivate var _videoFormat: Ldtx_YoutubeOutput_V1_H264Format? = nil
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "ldtx.youtube_output.v1"

nonisolated extension Ldtx_YoutubeOutput_V1_PCMSampleFormat: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0PCM_SAMPLE_FORMAT_UNSPECIFIED\0\u{1}PCM_SAMPLE_FORMAT_FLOAT32_INTERLEAVED\0")
}

nonisolated extension Ldtx_YoutubeOutput_V1_Context: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Context"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}session_id\0\u{1}generation\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.sessionID) }()
      case 2: try { try decoder.decodeSingularUInt64Field(value: &self.generation) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.sessionID.isEmpty {
      try visitor.visitSingularStringField(value: self.sessionID, fieldNumber: 1)
    }
    if self.generation != 0 {
      try visitor.visitSingularUInt64Field(value: self.generation, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Ldtx_YoutubeOutput_V1_Context, rhs: Ldtx_YoutubeOutput_V1_Context) -> Bool {
    if lhs.sessionID != rhs.sessionID {return false}
    if lhs.generation != rhs.generation {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Ldtx_YoutubeOutput_V1_Representation: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Representation"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}id\0\u{1}bandwidth\0\u{1}width\0\u{1}height\0\u{3}frame_rate\0\u{1}codecs\0\u{3}audio_sampling_rate\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.id) }()
      case 2: try { try decoder.decodeSingularInt32Field(value: &self.bandwidth) }()
      case 3: try { try decoder.decodeSingularInt32Field(value: &self.width) }()
      case 4: try { try decoder.decodeSingularInt32Field(value: &self.height) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self.frameRate) }()
      case 6: try { try decoder.decodeSingularStringField(value: &self.codecs) }()
      case 7: try { try decoder.decodeSingularInt32Field(value: &self.audioSamplingRate) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.id.isEmpty {
      try visitor.visitSingularStringField(value: self.id, fieldNumber: 1)
    }
    if self.bandwidth != 0 {
      try visitor.visitSingularInt32Field(value: self.bandwidth, fieldNumber: 2)
    }
    if self.width != 0 {
      try visitor.visitSingularInt32Field(value: self.width, fieldNumber: 3)
    }
    if self.height != 0 {
      try visitor.visitSingularInt32Field(value: self.height, fieldNumber: 4)
    }
    if !self.frameRate.isEmpty {
      try visitor.visitSingularStringField(value: self.frameRate, fieldNumber: 5)
    }
    if !self.codecs.isEmpty {
      try visitor.visitSingularStringField(value: self.codecs, fieldNumber: 6)
    }
    if self.audioSamplingRate != 0 {
      try visitor.visitSingularInt32Field(value: self.audioSamplingRate, fieldNumber: 7)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Ldtx_YoutubeOutput_V1_Representation, rhs: Ldtx_YoutubeOutput_V1_Representation) -> Bool {
    if lhs.id != rhs.id {return false}
    if lhs.bandwidth != rhs.bandwidth {return false}
    if lhs.width != rhs.width {return false}
    if lhs.height != rhs.height {return false}
    if lhs.frameRate != rhs.frameRate {return false}
    if lhs.codecs != rhs.codecs {return false}
    if lhs.audioSamplingRate != rhs.audioSamplingRate {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Ldtx_YoutubeOutput_V1_Bootstrap: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Bootstrap"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}protocol_version\0\u{1}context\0\u{1}endpoint\0\u{3}availability_start_time_milliseconds\0\u{1}timescale\0\u{3}segment_duration_seconds\0\u{3}start_number\0\u{3}media_template\0\u{1}representation\0\u{3}configuration_fingerprint\0\u{3}initialization_segment\0\u{3}persistence_identifier\0\u{3}next_media_time_seconds\0\u{3}shared_video_slot_count\0\u{3}shared_video_slot_size\0")

  fileprivate class _StorageClass {
    var _protocolVersion: UInt32 = 0
    var _context: Ldtx_YoutubeOutput_V1_Context? = nil
    var _endpoint: String = String()
    var _availabilityStartTimeMilliseconds: Int64 = 0
    var _timescale: Int32 = 0
    var _segmentDurationSeconds: Int32 = 0
    var _startNumber: Int32 = 0
    var _mediaTemplate: String = String()
    var _representation: Ldtx_YoutubeOutput_V1_Representation? = nil
    var _configurationFingerprint: String = String()
    var _initializationSegment: Data? = nil
    var _persistenceIdentifier: String = String()
    var _nextMediaTimeSeconds: Double? = nil
    var _sharedVideoSlotCount: Int32 = 0
    var _sharedVideoSlotSize: Int32 = 0

      // This property is used as the initial default value for new instances of the type.
      // The type itself is protecting the reference to its storage via CoW semantics.
      // This will force a copy to be made of this reference when the first mutation occurs;
      // hence, it is safe to mark this as `nonisolated(unsafe)`.
      static nonisolated(unsafe) let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _protocolVersion = source._protocolVersion
      _context = source._context
      _endpoint = source._endpoint
      _availabilityStartTimeMilliseconds = source._availabilityStartTimeMilliseconds
      _timescale = source._timescale
      _segmentDurationSeconds = source._segmentDurationSeconds
      _startNumber = source._startNumber
      _mediaTemplate = source._mediaTemplate
      _representation = source._representation
      _configurationFingerprint = source._configurationFingerprint
      _initializationSegment = source._initializationSegment
      _persistenceIdentifier = source._persistenceIdentifier
      _nextMediaTimeSeconds = source._nextMediaTimeSeconds
      _sharedVideoSlotCount = source._sharedVideoSlotCount
      _sharedVideoSlotSize = source._sharedVideoSlotSize
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 1: try { try decoder.decodeSingularUInt32Field(value: &_storage._protocolVersion) }()
        case 2: try { try decoder.decodeSingularMessageField(value: &_storage._context) }()
        case 3: try { try decoder.decodeSingularStringField(value: &_storage._endpoint) }()
        case 4: try { try decoder.decodeSingularInt64Field(value: &_storage._availabilityStartTimeMilliseconds) }()
        case 5: try { try decoder.decodeSingularInt32Field(value: &_storage._timescale) }()
        case 6: try { try decoder.decodeSingularInt32Field(value: &_storage._segmentDurationSeconds) }()
        case 7: try { try decoder.decodeSingularInt32Field(value: &_storage._startNumber) }()
        case 8: try { try decoder.decodeSingularStringField(value: &_storage._mediaTemplate) }()
        case 9: try { try decoder.decodeSingularMessageField(value: &_storage._representation) }()
        case 10: try { try decoder.decodeSingularStringField(value: &_storage._configurationFingerprint) }()
        case 11: try { try decoder.decodeSingularBytesField(value: &_storage._initializationSegment) }()
        case 12: try { try decoder.decodeSingularStringField(value: &_storage._persistenceIdentifier) }()
        case 13: try { try decoder.decodeSingularDoubleField(value: &_storage._nextMediaTimeSeconds) }()
        case 14: try { try decoder.decodeSingularInt32Field(value: &_storage._sharedVideoSlotCount) }()
        case 15: try { try decoder.decodeSingularInt32Field(value: &_storage._sharedVideoSlotSize) }()
        default: break
        }
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every if/case branch local when no optimizations
      // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
      // https://github.com/apple/swift-protobuf/issues/1182
      if _storage._protocolVersion != 0 {
        try visitor.visitSingularUInt32Field(value: _storage._protocolVersion, fieldNumber: 1)
      }
      try { if let v = _storage._context {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
      } }()
      if !_storage._endpoint.isEmpty {
        try visitor.visitSingularStringField(value: _storage._endpoint, fieldNumber: 3)
      }
      if _storage._availabilityStartTimeMilliseconds != 0 {
        try visitor.visitSingularInt64Field(value: _storage._availabilityStartTimeMilliseconds, fieldNumber: 4)
      }
      if _storage._timescale != 0 {
        try visitor.visitSingularInt32Field(value: _storage._timescale, fieldNumber: 5)
      }
      if _storage._segmentDurationSeconds != 0 {
        try visitor.visitSingularInt32Field(value: _storage._segmentDurationSeconds, fieldNumber: 6)
      }
      if _storage._startNumber != 0 {
        try visitor.visitSingularInt32Field(value: _storage._startNumber, fieldNumber: 7)
      }
      if !_storage._mediaTemplate.isEmpty {
        try visitor.visitSingularStringField(value: _storage._mediaTemplate, fieldNumber: 8)
      }
      try { if let v = _storage._representation {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 9)
      } }()
      if !_storage._configurationFingerprint.isEmpty {
        try visitor.visitSingularStringField(value: _storage._configurationFingerprint, fieldNumber: 10)
      }
      try { if let v = _storage._initializationSegment {
        try visitor.visitSingularBytesField(value: v, fieldNumber: 11)
      } }()
      if !_storage._persistenceIdentifier.isEmpty {
        try visitor.visitSingularStringField(value: _storage._persistenceIdentifier, fieldNumber: 12)
      }
      try { if let v = _storage._nextMediaTimeSeconds {
        try visitor.visitSingularDoubleField(value: v, fieldNumber: 13)
      } }()
      if _storage._sharedVideoSlotCount != 0 {
        try visitor.visitSingularInt32Field(value: _storage._sharedVideoSlotCount, fieldNumber: 14)
      }
      if _storage._sharedVideoSlotSize != 0 {
        try visitor.visitSingularInt32Field(value: _storage._sharedVideoSlotSize, fieldNumber: 15)
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Ldtx_YoutubeOutput_V1_Bootstrap, rhs: Ldtx_YoutubeOutput_V1_Bootstrap) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._protocolVersion != rhs_storage._protocolVersion {return false}
        if _storage._context != rhs_storage._context {return false}
        if _storage._endpoint != rhs_storage._endpoint {return false}
        if _storage._availabilityStartTimeMilliseconds != rhs_storage._availabilityStartTimeMilliseconds {return false}
        if _storage._timescale != rhs_storage._timescale {return false}
        if _storage._segmentDurationSeconds != rhs_storage._segmentDurationSeconds {return false}
        if _storage._startNumber != rhs_storage._startNumber {return false}
        if _storage._mediaTemplate != rhs_storage._mediaTemplate {return false}
        if _storage._representation != rhs_storage._representation {return false}
        if _storage._configurationFingerprint != rhs_storage._configurationFingerprint {return false}
        if _storage._initializationSegment != rhs_storage._initializationSegment {return false}
        if _storage._persistenceIdentifier != rhs_storage._persistenceIdentifier {return false}
        if _storage._nextMediaTimeSeconds != rhs_storage._nextMediaTimeSeconds {return false}
        if _storage._sharedVideoSlotCount != rhs_storage._sharedVideoSlotCount {return false}
        if _storage._sharedVideoSlotSize != rhs_storage._sharedVideoSlotSize {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Ldtx_YoutubeOutput_V1_SharedMemorySlice: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".SharedMemorySlice"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}slot\0\u{1}generation\0\u{1}offset\0\u{1}length\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt32Field(value: &self.slot) }()
      case 2: try { try decoder.decodeSingularUInt64Field(value: &self.generation) }()
      case 3: try { try decoder.decodeSingularInt32Field(value: &self.offset) }()
      case 4: try { try decoder.decodeSingularInt32Field(value: &self.length) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.slot != 0 {
      try visitor.visitSingularInt32Field(value: self.slot, fieldNumber: 1)
    }
    if self.generation != 0 {
      try visitor.visitSingularUInt64Field(value: self.generation, fieldNumber: 2)
    }
    if self.offset != 0 {
      try visitor.visitSingularInt32Field(value: self.offset, fieldNumber: 3)
    }
    if self.length != 0 {
      try visitor.visitSingularInt32Field(value: self.length, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Ldtx_YoutubeOutput_V1_SharedMemorySlice, rhs: Ldtx_YoutubeOutput_V1_SharedMemorySlice) -> Bool {
    if lhs.slot != rhs.slot {return false}
    if lhs.generation != rhs.generation {return false}
    if lhs.offset != rhs.offset {return false}
    if lhs.length != rhs.length {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Ldtx_YoutubeOutput_V1_FinishRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".FinishRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}context\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._context) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._context {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Ldtx_YoutubeOutput_V1_FinishRequest, rhs: Ldtx_YoutubeOutput_V1_FinishRequest) -> Bool {
    if lhs._context != rhs._context {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Ldtx_YoutubeOutput_V1_Reply: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Reply"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}context\0\u{1}sequence\0\u{3}next_media_segment_number\0\u{3}initialization_segment\0\u{3}configuration_fingerprint\0\u{3}event_description\0\u{3}error_description\0\u{3}availability_start_time_milliseconds\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._context) }()
      case 2: try { try decoder.decodeSingularUInt64Field(value: &self._sequence) }()
      case 3: try { try decoder.decodeSingularInt32Field(value: &self._nextMediaSegmentNumber) }()
      case 4: try { try decoder.decodeSingularBytesField(value: &self._initializationSegment) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self._configurationFingerprint) }()
      case 6: try { try decoder.decodeSingularStringField(value: &self._eventDescription) }()
      case 7: try { try decoder.decodeSingularStringField(value: &self._errorDescription) }()
      case 8: try { try decoder.decodeSingularInt64Field(value: &self._availabilityStartTimeMilliseconds) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._context {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._sequence {
      try visitor.visitSingularUInt64Field(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._nextMediaSegmentNumber {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 3)
    } }()
    try { if let v = self._initializationSegment {
      try visitor.visitSingularBytesField(value: v, fieldNumber: 4)
    } }()
    try { if let v = self._configurationFingerprint {
      try visitor.visitSingularStringField(value: v, fieldNumber: 5)
    } }()
    try { if let v = self._eventDescription {
      try visitor.visitSingularStringField(value: v, fieldNumber: 6)
    } }()
    try { if let v = self._errorDescription {
      try visitor.visitSingularStringField(value: v, fieldNumber: 7)
    } }()
    try { if let v = self._availabilityStartTimeMilliseconds {
      try visitor.visitSingularInt64Field(value: v, fieldNumber: 8)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Ldtx_YoutubeOutput_V1_Reply, rhs: Ldtx_YoutubeOutput_V1_Reply) -> Bool {
    if lhs._context != rhs._context {return false}
    if lhs._sequence != rhs._sequence {return false}
    if lhs._nextMediaSegmentNumber != rhs._nextMediaSegmentNumber {return false}
    if lhs._initializationSegment != rhs._initializationSegment {return false}
    if lhs._configurationFingerprint != rhs._configurationFingerprint {return false}
    if lhs._eventDescription != rhs._eventDescription {return false}
    if lhs._errorDescription != rhs._errorDescription {return false}
    if lhs._availabilityStartTimeMilliseconds != rhs._availabilityStartTimeMilliseconds {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Ldtx_YoutubeOutput_V1_ResetRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ResetRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}context\0\u{1}reason\0\u{3}next_media_segment_number\0\u{3}initialization_segment\0\u{3}configuration_fingerprint\0\u{3}availability_start_time_milliseconds\0\u{3}next_media_time_seconds\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._context) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.reason) }()
      case 3: try { try decoder.decodeSingularInt32Field(value: &self._nextMediaSegmentNumber) }()
      case 4: try { try decoder.decodeSingularBytesField(value: &self._initializationSegment) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self._configurationFingerprint) }()
      case 6: try { try decoder.decodeSingularInt64Field(value: &self._availabilityStartTimeMilliseconds) }()
      case 7: try { try decoder.decodeSingularDoubleField(value: &self._nextMediaTimeSeconds) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._context {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    if !self.reason.isEmpty {
      try visitor.visitSingularStringField(value: self.reason, fieldNumber: 2)
    }
    try { if let v = self._nextMediaSegmentNumber {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 3)
    } }()
    try { if let v = self._initializationSegment {
      try visitor.visitSingularBytesField(value: v, fieldNumber: 4)
    } }()
    try { if let v = self._configurationFingerprint {
      try visitor.visitSingularStringField(value: v, fieldNumber: 5)
    } }()
    try { if let v = self._availabilityStartTimeMilliseconds {
      try visitor.visitSingularInt64Field(value: v, fieldNumber: 6)
    } }()
    try { if let v = self._nextMediaTimeSeconds {
      try visitor.visitSingularDoubleField(value: v, fieldNumber: 7)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Ldtx_YoutubeOutput_V1_ResetRequest, rhs: Ldtx_YoutubeOutput_V1_ResetRequest) -> Bool {
    if lhs._context != rhs._context {return false}
    if lhs.reason != rhs.reason {return false}
    if lhs._nextMediaSegmentNumber != rhs._nextMediaSegmentNumber {return false}
    if lhs._initializationSegment != rhs._initializationSegment {return false}
    if lhs._configurationFingerprint != rhs._configurationFingerprint {return false}
    if lhs._availabilityStartTimeMilliseconds != rhs._availabilityStartTimeMilliseconds {return false}
    if lhs._nextMediaTimeSeconds != rhs._nextMediaTimeSeconds {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Ldtx_YoutubeOutput_V1_MediaTime: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".MediaTime"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}value\0\u{1}timescale\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt64Field(value: &self.value) }()
      case 2: try { try decoder.decodeSingularInt32Field(value: &self.timescale) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.value != 0 {
      try visitor.visitSingularInt64Field(value: self.value, fieldNumber: 1)
    }
    if self.timescale != 0 {
      try visitor.visitSingularInt32Field(value: self.timescale, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Ldtx_YoutubeOutput_V1_MediaTime, rhs: Ldtx_YoutubeOutput_V1_MediaTime) -> Bool {
    if lhs.value != rhs.value {return false}
    if lhs.timescale != rhs.timescale {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Ldtx_YoutubeOutput_V1_H264Format: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".H264Format"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}parameter_sets\0\u{3}nal_unit_header_length\0\u{1}width\0\u{1}height\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedBytesField(value: &self.parameterSets) }()
      case 2: try { try decoder.decodeSingularInt32Field(value: &self.nalUnitHeaderLength) }()
      case 3: try { try decoder.decodeSingularInt32Field(value: &self.width) }()
      case 4: try { try decoder.decodeSingularInt32Field(value: &self.height) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.parameterSets.isEmpty {
      try visitor.visitRepeatedBytesField(value: self.parameterSets, fieldNumber: 1)
    }
    if self.nalUnitHeaderLength != 0 {
      try visitor.visitSingularInt32Field(value: self.nalUnitHeaderLength, fieldNumber: 2)
    }
    if self.width != 0 {
      try visitor.visitSingularInt32Field(value: self.width, fieldNumber: 3)
    }
    if self.height != 0 {
      try visitor.visitSingularInt32Field(value: self.height, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Ldtx_YoutubeOutput_V1_H264Format, rhs: Ldtx_YoutubeOutput_V1_H264Format) -> Bool {
    if lhs.parameterSets != rhs.parameterSets {return false}
    if lhs.nalUnitHeaderLength != rhs.nalUnitHeaderLength {return false}
    if lhs.width != rhs.width {return false}
    if lhs.height != rhs.height {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Ldtx_YoutubeOutput_V1_H264AccessUnit: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".H264AccessUnit"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}presentation_time\0\u{3}decode_time\0\u{1}duration\0\u{3}key_frame\0\u{3}avcc_data\0\u{3}shared_memory\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._presentationTime) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._decodeTime) }()
      case 3: try { try decoder.decodeSingularMessageField(value: &self._duration) }()
      case 4: try { try decoder.decodeSingularBoolField(value: &self.keyFrame) }()
      case 5: try { try decoder.decodeSingularBytesField(value: &self.avccData) }()
      case 6: try { try decoder.decodeSingularMessageField(value: &self._sharedMemory) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._presentationTime {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._decodeTime {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._duration {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    } }()
    if self.keyFrame != false {
      try visitor.visitSingularBoolField(value: self.keyFrame, fieldNumber: 4)
    }
    if !self.avccData.isEmpty {
      try visitor.visitSingularBytesField(value: self.avccData, fieldNumber: 5)
    }
    try { if let v = self._sharedMemory {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 6)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Ldtx_YoutubeOutput_V1_H264AccessUnit, rhs: Ldtx_YoutubeOutput_V1_H264AccessUnit) -> Bool {
    if lhs._presentationTime != rhs._presentationTime {return false}
    if lhs._decodeTime != rhs._decodeTime {return false}
    if lhs._duration != rhs._duration {return false}
    if lhs.keyFrame != rhs.keyFrame {return false}
    if lhs.avccData != rhs.avccData {return false}
    if lhs._sharedMemory != rhs._sharedMemory {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Ldtx_YoutubeOutput_V1_PCMBuffer: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".PCMBuffer"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}presentation_time\0\u{1}duration\0\u{3}sample_rate\0\u{3}channel_count\0\u{3}frame_count\0\u{3}sample_format\0\u{1}data\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._presentationTime) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._duration) }()
      case 3: try { try decoder.decodeSingularInt32Field(value: &self.sampleRate) }()
      case 4: try { try decoder.decodeSingularInt32Field(value: &self.channelCount) }()
      case 5: try { try decoder.decodeSingularInt32Field(value: &self.frameCount) }()
      case 6: try { try decoder.decodeSingularEnumField(value: &self.sampleFormat) }()
      case 7: try { try decoder.decodeSingularBytesField(value: &self.data) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._presentationTime {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._duration {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    if self.sampleRate != 0 {
      try visitor.visitSingularInt32Field(value: self.sampleRate, fieldNumber: 3)
    }
    if self.channelCount != 0 {
      try visitor.visitSingularInt32Field(value: self.channelCount, fieldNumber: 4)
    }
    if self.frameCount != 0 {
      try visitor.visitSingularInt32Field(value: self.frameCount, fieldNumber: 5)
    }
    if self.sampleFormat != .unspecified {
      try visitor.visitSingularEnumField(value: self.sampleFormat, fieldNumber: 6)
    }
    if !self.data.isEmpty {
      try visitor.visitSingularBytesField(value: self.data, fieldNumber: 7)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Ldtx_YoutubeOutput_V1_PCMBuffer, rhs: Ldtx_YoutubeOutput_V1_PCMBuffer) -> Bool {
    if lhs._presentationTime != rhs._presentationTime {return false}
    if lhs._duration != rhs._duration {return false}
    if lhs.sampleRate != rhs.sampleRate {return false}
    if lhs.channelCount != rhs.channelCount {return false}
    if lhs.frameCount != rhs.frameCount {return false}
    if lhs.sampleFormat != rhs.sampleFormat {return false}
    if lhs.data != rhs.data {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Ldtx_YoutubeOutput_V1_MediaBatch: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".MediaBatch"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}protocol_version\0\u{1}context\0\u{1}sequence\0\u{3}video_format\0\u{1}video\0\u{1}audio\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt32Field(value: &self.protocolVersion) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._context) }()
      case 3: try { try decoder.decodeSingularUInt64Field(value: &self.sequence) }()
      case 4: try { try decoder.decodeSingularMessageField(value: &self._videoFormat) }()
      case 5: try { try decoder.decodeRepeatedMessageField(value: &self.video) }()
      case 6: try { try decoder.decodeRepeatedMessageField(value: &self.audio) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.protocolVersion != 0 {
      try visitor.visitSingularUInt32Field(value: self.protocolVersion, fieldNumber: 1)
    }
    try { if let v = self._context {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    if self.sequence != 0 {
      try visitor.visitSingularUInt64Field(value: self.sequence, fieldNumber: 3)
    }
    try { if let v = self._videoFormat {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
    } }()
    if !self.video.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.video, fieldNumber: 5)
    }
    if !self.audio.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.audio, fieldNumber: 6)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Ldtx_YoutubeOutput_V1_MediaBatch, rhs: Ldtx_YoutubeOutput_V1_MediaBatch) -> Bool {
    if lhs.protocolVersion != rhs.protocolVersion {return false}
    if lhs._context != rhs._context {return false}
    if lhs.sequence != rhs.sequence {return false}
    if lhs._videoFormat != rhs._videoFormat {return false}
    if lhs.video != rhs.video {return false}
    if lhs.audio != rhs.audio {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
