# SPDX-FileCopyrightText: 2026 Kaito Udagawa <umireon@kaito.tokyo>
#
# SPDX-License-Identifier: Apache-2.0

name: LDTX

configs:
  Debug: debug
  CI: debug
  Release: release
  Distribution: release

options:
  bundleIdPrefix: tokyo.kaito.ldtx
  defaultConfig: Debug
  deploymentTarget:
    macOS: "26.0"
  createIntermediateGroups: true
  defaultSourceDirectoryType: syncedFolder

packages:
  AppAuth-iOS:
    url: https://github.com/openid/AppAuth-iOS.git
    exactVersion: 2.1.0
  SwiftProtobuf:
    url: https://github.com/apple/swift-protobuf.git
    exactVersion: 1.38.1
  swift-argument-parser:
    url: https://github.com/apple/swift-argument-parser
    exactVersion: 1.8.2

settings:
  base:
    SWIFT_VERSION: "6.0"
    MACOSX_DEPLOYMENT_TARGET: "26.0"
    CURRENT_PROJECT_VERSION: "1"
    MARKETING_VERSION: "0.1.50"
    DEVELOPMENT_TEAM: 4HMJS6J4MZ
    CODE_SIGN_STYLE: Automatic
    DEAD_CODE_STRIPPING: "YES"
    ENABLE_USER_SCRIPT_SANDBOXING: "YES"
    STRING_CATALOG_GENERATE_SYMBOLS: "YES"
    SWIFT_OBJC_INTEROP_MODE: objcxx

include:
  - path: project/frameworks.yml
    relativePaths: false
  - path: project/app.yml
    relativePaths: false
  - path: project/extensions.yml
    relativePaths: false
  - path: project/services.yml
    relativePaths: false
  - path: project/tests-easy.yml
    relativePaths: false
  - path: project/tests-hard.yml
    relativePaths: false
  - path: project/tests-audio-engine.yml
    relativePaths: false
