version = 1

[[annotations]]
path = [
  "**/OFL.txt",
  "NOTICE",
]
SPDX-FileCopyrightText = "NONE"
SPDX-License-Identifier = "LicenseRef-Not-Copyrightable"

[[annotations]]
path = [
  ".swift-format",
  "**/module_mappings.asciipb",
  "Package.resolved",
  "requirements-dev.lock",
  "Resources/**/*.json",
  "Resources/Shared/About/Credits.rtf",
]
SPDX-FileCopyrightText = "2026 Kaito Udagawa <umireon@kaito.tokyo>"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "Sources/LDTXFullAppFeatures/MediaPipeSelfieSegmenter.mlpackage/**",
]
SPDX-FileCopyrightText = [
  "2026 Kaito Udagawa <umireon@kaito.tokyo>",
  "Google LLC"
]
SPDX-License-Identifier = "Apache-2.0"
