// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: workspace.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

// SPDX-FileCopyrightText: 2026 Kaito Udagawa <umireon@kaito.tokyo>
//
// SPDX-License-Identifier: Apache-2.0

import SwiftProtobuf

import LDTXProgram

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public nonisolated enum Ldtx_Workspace_V1_InputDeviceKind: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case unspecified // = 0
  case video // = 1
  case audio // = 2
  case UNRECOGNIZED(Int)

  public init() {
    self = .unspecified
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .video
    case 2: self = .audio
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .video: return 1
    case .audio: return 2
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [Ldtx_Workspace_V1_InputDeviceKind] = [
    .unspecified,
    .video,
    .audio,
  ]

}

public nonisolated enum Ldtx_Workspace_V1_SideTrackRecordingPolicy: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case unspecified // = 0
  case enabled // = 1
  case disabled // = 2
  case UNRECOGNIZED(Int)

  public init() {
    self = .unspecified
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .enabled
    case 2: self = .disabled
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .enabled: return 1
    case .disabled: return 2
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [Ldtx_Workspace_V1_SideTrackRecordingPolicy] = [
    .unspecified,
    .enabled,
    .disabled,
  ]

}

public nonisolated struct Ldtx_Workspace_V1_Workspace: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var id: String = String()

  public var name: String = String()

  public var programs: [Ldtx_Workspace_V1_ProgramRecord] = []

  public var programArguments: [Ldtx_Workspace_V1_ProgramArgumentsRecord] = []

  public var inputDevices: [Ldtx_Workspace_V1_InputDeviceRecord] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public nonisolated struct Ldtx_Workspace_V1_ProgramRecord: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var name: String = String()

  public var canvasWidth: UInt32 = 0

  public var canvasHeight: UInt32 = 0

  public var frameRateNumerator: UInt32 = 0

  public var frameRateDenominator: UInt32 = 0

  public var program: LDTXProgram.Ldtx_Program_V1_Program {
    get {_program ?? LDTXProgram.Ldtx_Program_V1_Program()}
    set {_program = newValue}
  }
  /// Returns true if `program` has been explicitly set.
  public var hasProgram: Bool {self._program != nil}
  /// Clears the value of `program`. Subsequent reads from it will return its default value.
  public mutating func clearProgram() {self._program = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _program: LDTXProgram.Ldtx_Program_V1_Program? = nil
}

public nonisolated struct Ldtx_Workspace_V1_ProgramArgumentsRecord: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var name: String = String()

  public var arguments: LDTXProgram.Ldtx_Program_Persistence_V1_ProgramArguments {
    get {_arguments ?? LDTXProgram.Ldtx_Program_Persistence_V1_ProgramArguments()}
    set {_arguments = newValue}
  }
  /// Returns true if `arguments` has been explicitly set.
  public var hasArguments: Bool {self._arguments != nil}
  /// Clears the value of `arguments`. Subsequent reads from it will return its default value.
  public mutating func clearArguments() {self._arguments = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _arguments: LDTXProgram.Ldtx_Program_Persistence_V1_ProgramArguments? = nil
}

public nonisolated struct Ldtx_Workspace_V1_InputDeviceRecord: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var name: String = String()

  public var kind: Ldtx_Workspace_V1_InputDeviceKind = .unspecified

  public var sideTrackRecordingPolicy: Ldtx_Workspace_V1_SideTrackRecordingPolicy = .unspecified

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "ldtx.workspace.v1"

nonisolated extension Ldtx_Workspace_V1_InputDeviceKind: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0INPUT_DEVICE_KIND_UNSPECIFIED\0\u{1}INPUT_DEVICE_KIND_VIDEO\0\u{1}INPUT_DEVICE_KIND_AUDIO\0")
}

nonisolated extension Ldtx_Workspace_V1_SideTrackRecordingPolicy: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0SIDE_TRACK_RECORDING_POLICY_UNSPECIFIED\0\u{1}SIDE_TRACK_RECORDING_POLICY_ENABLED\0\u{1}SIDE_TRACK_RECORDING_POLICY_DISABLED\0")
}

nonisolated extension Ldtx_Workspace_V1_Workspace: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Workspace"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}id\0\u{1}name\0\u{1}programs\0\u{3}program_arguments\0\u{3}input_devices\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.id) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.name) }()
      case 3: try { try decoder.decodeRepeatedMessageField(value: &self.programs) }()
      case 4: try { try decoder.decodeRepeatedMessageField(value: &self.programArguments) }()
      case 5: try { try decoder.decodeRepeatedMessageField(value: &self.inputDevices) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.id.isEmpty {
      try visitor.visitSingularStringField(value: self.id, fieldNumber: 1)
    }
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 2)
    }
    if !self.programs.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.programs, fieldNumber: 3)
    }
    if !self.programArguments.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.programArguments, fieldNumber: 4)
    }
    if !self.inputDevices.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.inputDevices, fieldNumber: 5)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Ldtx_Workspace_V1_Workspace, rhs: Ldtx_Workspace_V1_Workspace) -> Bool {
    if lhs.id != rhs.id {return false}
    if lhs.name != rhs.name {return false}
    if lhs.programs != rhs.programs {return false}
    if lhs.programArguments != rhs.programArguments {return false}
    if lhs.inputDevices != rhs.inputDevices {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Ldtx_Workspace_V1_ProgramRecord: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ProgramRecord"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}name\0\u{3}canvas_width\0\u{3}canvas_height\0\u{3}frame_rate_numerator\0\u{3}frame_rate_denominator\0\u{1}program\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.name) }()
      case 2: try { try decoder.decodeSingularUInt32Field(value: &self.canvasWidth) }()
      case 3: try { try decoder.decodeSingularUInt32Field(value: &self.canvasHeight) }()
      case 4: try { try decoder.decodeSingularUInt32Field(value: &self.frameRateNumerator) }()
      case 5: try { try decoder.decodeSingularUInt32Field(value: &self.frameRateDenominator) }()
      case 6: try { try decoder.decodeSingularMessageField(value: &self._program) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 1)
    }
    if self.canvasWidth != 0 {
      try visitor.visitSingularUInt32Field(value: self.canvasWidth, fieldNumber: 2)
    }
    if self.canvasHeight != 0 {
      try visitor.visitSingularUInt32Field(value: self.canvasHeight, fieldNumber: 3)
    }
    if self.frameRateNumerator != 0 {
      try visitor.visitSingularUInt32Field(value: self.frameRateNumerator, fieldNumber: 4)
    }
    if self.frameRateDenominator != 0 {
      try visitor.visitSingularUInt32Field(value: self.frameRateDenominator, fieldNumber: 5)
    }
    try { if let v = self._program {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 6)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Ldtx_Workspace_V1_ProgramRecord, rhs: Ldtx_Workspace_V1_ProgramRecord) -> Bool {
    if lhs.name != rhs.name {return false}
    if lhs.canvasWidth != rhs.canvasWidth {return false}
    if lhs.canvasHeight != rhs.canvasHeight {return false}
    if lhs.frameRateNumerator != rhs.frameRateNumerator {return false}
    if lhs.frameRateDenominator != rhs.frameRateDenominator {return false}
    if lhs._program != rhs._program {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Ldtx_Workspace_V1_ProgramArgumentsRecord: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ProgramArgumentsRecord"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}name\0\u{1}arguments\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.name) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._arguments) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 1)
    }
    try { if let v = self._arguments {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Ldtx_Workspace_V1_ProgramArgumentsRecord, rhs: Ldtx_Workspace_V1_ProgramArgumentsRecord) -> Bool {
    if lhs.name != rhs.name {return false}
    if lhs._arguments != rhs._arguments {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Ldtx_Workspace_V1_InputDeviceRecord: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".InputDeviceRecord"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}name\0\u{1}kind\0\u{3}side_track_recording_policy\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.name) }()
      case 2: try { try decoder.decodeSingularEnumField(value: &self.kind) }()
      case 3: try { try decoder.decodeSingularEnumField(value: &self.sideTrackRecordingPolicy) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 1)
    }
    if self.kind != .unspecified {
      try visitor.visitSingularEnumField(value: self.kind, fieldNumber: 2)
    }
    if self.sideTrackRecordingPolicy != .unspecified {
      try visitor.visitSingularEnumField(value: self.sideTrackRecordingPolicy, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Ldtx_Workspace_V1_InputDeviceRecord, rhs: Ldtx_Workspace_V1_InputDeviceRecord) -> Bool {
    if lhs.name != rhs.name {return false}
    if lhs.kind != rhs.kind {return false}
    if lhs.sideTrackRecordingPolicy != rhs.sideTrackRecordingPolicy {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
