// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: workspace.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

// SPDX-FileCopyrightText: 2026 Kaito Udagawa <umireon@kaito.tokyo>
//
// SPDX-License-Identifier: Apache-2.0

import SwiftProtobuf

import LDTXProgram

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public nonisolated enum Ldtx_Workspace_V1_InputDeviceKind: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case unspecified // = 0
  case video // = 1
  case audio // = 2
  case UNRECOGNIZED(Int)

  public init() {
    self = .unspecified
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .video
    case 2: self = .audio
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .video: return 1
    case .audio: return 2
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [Ldtx_Workspace_V1_InputDeviceKind] = [
    .unspecified,
    .video,
    .audio,
  ]

}

public nonisolated enum Ldtx_Workspace_V1_SideTrackRecordingPolicy: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case unspecified // = 0
  case enabled // = 1
  case disabled // = 2
  case UNRECOGNIZED(Int)

  public init() {
    self = .unspecified
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .enabled
    case 2: self = .disabled
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .enabled: return 1
    case .disabled: return 2
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [Ldtx_Workspace_V1_SideTrackRecordingPolicy] = [
    .unspecified,
    .enabled,
    .disabled,
  ]

}

public nonisolated enum Ldtx_Workspace_V1_BackgroundRemovalPolicy: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case unspecified // = 0
  case enabled // = 1
  case disabled // = 2
  case UNRECOGNIZED(Int)

  public init() {
    self = .unspecified
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .enabled
    case 2: self = .disabled
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .enabled: return 1
    case .disabled: return 2
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [Ldtx_Workspace_V1_BackgroundRemovalPolicy] = [
    .unspecified,
    .enabled,
    .disabled,
  ]

}

public nonisolated enum Ldtx_Workspace_V1_ColorRangePolicy: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case unspecified // = 0
  case videoRange // = 1
  case fullRange // = 2
  case UNRECOGNIZED(Int)

  public init() {
    self = .unspecified
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .videoRange
    case 2: self = .fullRange
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .videoRange: return 1
    case .fullRange: return 2
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [Ldtx_Workspace_V1_ColorRangePolicy] = [
    .unspecified,
    .videoRange,
    .fullRange,
  ]

}

public nonisolated struct Ldtx_Workspace_V1_Workspace: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var id: String = String()

  public var name: String = String()

  public var programs: [Ldtx_Workspace_V1_ProgramRecord] = []

  /// Legacy preferences field. New writers store this in WorkspacePreferences.
  ///
  /// NOTE: This field was marked as deprecated in the .proto file.
  public var programPreferences: [Ldtx_Workspace_V1_ProgramPreferencesRecord] = []

  public var inputDevices: [Ldtx_Workspace_V1_InputDeviceRecord] = []

  public var audioChannels: [LDTXProgram.Ldtx_Program_V1_ProgramAudioChannel] = []

  public var visions: [Ldtx_Workspace_V1_VisionRecord] = []

  public var automations: [Ldtx_Workspace_V1_AutomationRecord] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public nonisolated struct Ldtx_Workspace_V1_WorkspacePreferences: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var programPreferences: [Ldtx_Workspace_V1_ProgramPreferencesRecord] = []

  public var physicalDeviceIdsByInputDeviceID: Dictionary<String,String> = [:]

  public var inputCameraDeviceMappings: Dictionary<String,String> = [:]

  public var inputAudioDeviceMappings: Dictionary<String,String> = [:]

  public var inputAudioMonitorChannelKeys: [String] = []

  public var selectedProgramName: String {
    get {_selectedProgramName ?? String()}
    set {_selectedProgramName = newValue}
  }
  /// Returns true if `selectedProgramName` has been explicitly set.
  public var hasSelectedProgramName: Bool {self._selectedProgramName != nil}
  /// Clears the value of `selectedProgramName`. Subsequent reads from it will return its default value.
  public mutating func clearSelectedProgramName() {self._selectedProgramName = nil}

  public var output: Ldtx_Workspace_V1_OutputPreferences {
    get {_output ?? Ldtx_Workspace_V1_OutputPreferences()}
    set {_output = newValue}
  }
  /// Returns true if `output` has been explicitly set.
  public var hasOutput: Bool {self._output != nil}
  /// Clears the value of `output`. Subsequent reads from it will return its default value.
  public mutating func clearOutput() {self._output = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _selectedProgramName: String? = nil
  fileprivate var _output: Ldtx_Workspace_V1_OutputPreferences? = nil
}

public nonisolated struct Ldtx_Workspace_V1_OutputPreferences: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var captureOutputMode: String = String()

  public var existingBroadcastID: String = String()

  public var streamTitle: String = String()

  public var streamDescription: String = String()

  public var prefersColorPreview: Bool = false

  public var localOutputBaseDirectoryPath: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public nonisolated struct Ldtx_Workspace_V1_VisionRecord: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var id: String = String()

  public var name: String = String()

  public var source: Ldtx_Workspace_V1_VisionRecord.OneOf_Source? = nil

  public var currentProgramOutput: Bool {
    get {
      if case .currentProgramOutput(let v)? = source {return v}
      return false
    }
    set {source = .currentProgramOutput(newValue)}
  }

  public var inputDeviceID: String {
    get {
      if case .inputDeviceID(let v)? = source {return v}
      return String()
    }
    set {source = .inputDeviceID(newValue)}
  }

  public var modelRepositoryID: String = String()

  public var modelRevision: String {
    get {_modelRevision ?? String()}
    set {_modelRevision = newValue}
  }
  /// Returns true if `modelRevision` has been explicitly set.
  public var hasModelRevision: Bool {self._modelRevision != nil}
  /// Clears the value of `modelRevision`. Subsequent reads from it will return its default value.
  public mutating func clearModelRevision() {self._modelRevision = nil}

  /// Legacy field. Decode as system_prompt when system_prompt is absent.
  public var prompt: String = String()

  public var systemPrompt: String = String()

  public var userPrompt: String = String()

  /// Zero means manual updates.
  public var updateIntervalSeconds: Double = 0

  public var stopsAtNewline: Bool = false

  public var postActionAutomationID: String {
    get {_postActionAutomationID ?? String()}
    set {_postActionAutomationID = newValue}
  }
  /// Returns true if `postActionAutomationID` has been explicitly set.
  public var hasPostActionAutomationID: Bool {self._postActionAutomationID != nil}
  /// Clears the value of `postActionAutomationID`. Subsequent reads from it will return its default value.
  public mutating func clearPostActionAutomationID() {self._postActionAutomationID = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public nonisolated enum OneOf_Source: Equatable, Sendable {
    case currentProgramOutput(Bool)
    case inputDeviceID(String)

  }

  public init() {}

  fileprivate var _modelRevision: String? = nil
  fileprivate var _postActionAutomationID: String? = nil
}

public nonisolated struct Ldtx_Workspace_V1_AutomationRecord: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var id: String = String()

  public var name: String = String()

  public var isEnabled: Bool = false

  public var trigger: Ldtx_Workspace_V1_AutomationTrigger {
    get {_trigger ?? Ldtx_Workspace_V1_AutomationTrigger()}
    set {_trigger = newValue}
  }
  /// Returns true if `trigger` has been explicitly set.
  public var hasTrigger: Bool {self._trigger != nil}
  /// Clears the value of `trigger`. Subsequent reads from it will return its default value.
  public mutating func clearTrigger() {self._trigger = nil}

  public var actions: [Ldtx_Workspace_V1_AutomationAction] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _trigger: Ldtx_Workspace_V1_AutomationTrigger? = nil
}

public nonisolated struct Ldtx_Workspace_V1_AutomationTrigger: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var definition: Ldtx_Workspace_V1_AutomationTrigger.OneOf_Definition? = nil

  public var manual: Bool {
    get {
      if case .manual(let v)? = definition {return v}
      return false
    }
    set {definition = .manual(newValue)}
  }

  public var intervalSeconds: Double {
    get {
      if case .intervalSeconds(let v)? = definition {return v}
      return 0
    }
    set {definition = .intervalSeconds(newValue)}
  }

  public var visionResultChangedID: String {
    get {
      if case .visionResultChangedID(let v)? = definition {return v}
      return String()
    }
    set {definition = .visionResultChangedID(newValue)}
  }

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public nonisolated enum OneOf_Definition: Equatable, Sendable {
    case manual(Bool)
    case intervalSeconds(Double)
    case visionResultChangedID(String)

  }

  public init() {}
}

public nonisolated struct Ldtx_Workspace_V1_AutomationAction: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var id: String = String()

  public var definition: Ldtx_Workspace_V1_AutomationAction.OneOf_Definition? = nil

  public var analyzeVisionID: String {
    get {
      if case .analyzeVisionID(let v)? = definition {return v}
      return String()
    }
    set {definition = .analyzeVisionID(newValue)}
  }

  public var selectInputDeviceID: String {
    get {
      if case .selectInputDeviceID(let v)? = definition {return v}
      return String()
    }
    set {definition = .selectInputDeviceID(newValue)}
  }

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public nonisolated enum OneOf_Definition: Equatable, Sendable {
    case analyzeVisionID(String)
    case selectInputDeviceID(String)

  }

  public init() {}
}

public nonisolated struct Ldtx_Workspace_V1_ProgramRecord: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var name: String = String()

  public var canvasWidth: UInt32 = 0

  public var canvasHeight: UInt32 = 0

  public var frameRateNumerator: UInt32 = 0

  public var frameRateDenominator: UInt32 = 0

  public var program: LDTXProgram.Ldtx_Program_V1_Program {
    get {_program ?? LDTXProgram.Ldtx_Program_V1_Program()}
    set {_program = newValue}
  }
  /// Returns true if `program` has been explicitly set.
  public var hasProgram: Bool {self._program != nil}
  /// Clears the value of `program`. Subsequent reads from it will return its default value.
  public mutating func clearProgram() {self._program = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _program: LDTXProgram.Ldtx_Program_V1_Program? = nil
}

public nonisolated struct Ldtx_Workspace_V1_ProgramPreferencesRecord: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var name: String = String()

  public var preferences: LDTXProgram.Ldtx_Program_Persistence_V1_ProgramPreferences {
    get {_preferences ?? LDTXProgram.Ldtx_Program_Persistence_V1_ProgramPreferences()}
    set {_preferences = newValue}
  }
  /// Returns true if `preferences` has been explicitly set.
  public var hasPreferences: Bool {self._preferences != nil}
  /// Clears the value of `preferences`. Subsequent reads from it will return its default value.
  public mutating func clearPreferences() {self._preferences = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _preferences: LDTXProgram.Ldtx_Program_Persistence_V1_ProgramPreferences? = nil
}

public nonisolated struct Ldtx_Workspace_V1_InputDeviceRecord: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var name: String = String()

  public var kind: Ldtx_Workspace_V1_InputDeviceKind = .unspecified

  public var sideTrackRecordingPolicy: Ldtx_Workspace_V1_SideTrackRecordingPolicy = .unspecified

  public var id: String = String()

  /// Legacy preferences field. New writers store this in WorkspacePreferences.
  ///
  /// NOTE: This field was marked as deprecated in the .proto file.
  public var physicalDeviceID: String = String()

  public var backgroundRemovalPolicy: Ldtx_Workspace_V1_BackgroundRemovalPolicy = .unspecified

  public var colorRangePolicy: Ldtx_Workspace_V1_ColorRangePolicy = .unspecified

  public var captureWidthOverride: UInt32 = 0

  public var captureHeightOverride: UInt32 = 0

  public var captureFrameRateOverride: UInt32 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "ldtx.workspace.v1"

nonisolated extension Ldtx_Workspace_V1_InputDeviceKind: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0INPUT_DEVICE_KIND_UNSPECIFIED\0\u{1}INPUT_DEVICE_KIND_VIDEO\0\u{1}INPUT_DEVICE_KIND_AUDIO\0")
}

nonisolated extension Ldtx_Workspace_V1_SideTrackRecordingPolicy: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0SIDE_TRACK_RECORDING_POLICY_UNSPECIFIED\0\u{1}SIDE_TRACK_RECORDING_POLICY_ENABLED\0\u{1}SIDE_TRACK_RECORDING_POLICY_DISABLED\0")
}

nonisolated extension Ldtx_Workspace_V1_BackgroundRemovalPolicy: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0BACKGROUND_REMOVAL_POLICY_UNSPECIFIED\0\u{1}BACKGROUND_REMOVAL_POLICY_ENABLED\0\u{1}BACKGROUND_REMOVAL_POLICY_DISABLED\0")
}

nonisolated extension Ldtx_Workspace_V1_ColorRangePolicy: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0COLOR_RANGE_POLICY_UNSPECIFIED\0\u{1}COLOR_RANGE_POLICY_VIDEO_RANGE\0\u{1}COLOR_RANGE_POLICY_FULL_RANGE\0")
}

nonisolated extension Ldtx_Workspace_V1_Workspace: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Workspace"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}id\0\u{1}name\0\u{1}programs\0\u{3}program_preferences\0\u{3}input_devices\0\u{3}audio_channels\0\u{1}visions\0\u{1}automations\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.id) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.name) }()
      case 3: try { try decoder.decodeRepeatedMessageField(value: &self.programs) }()
      case 4: try { try decoder.decodeRepeatedMessageField(value: &self.programPreferences) }()
      case 5: try { try decoder.decodeRepeatedMessageField(value: &self.inputDevices) }()
      case 6: try { try decoder.decodeRepeatedMessageField(value: &self.audioChannels) }()
      case 7: try { try decoder.decodeRepeatedMessageField(value: &self.visions) }()
      case 8: try { try decoder.decodeRepeatedMessageField(value: &self.automations) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.id.isEmpty {
      try visitor.visitSingularStringField(value: self.id, fieldNumber: 1)
    }
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 2)
    }
    if !self.programs.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.programs, fieldNumber: 3)
    }
    if !self.programPreferences.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.programPreferences, fieldNumber: 4)
    }
    if !self.inputDevices.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.inputDevices, fieldNumber: 5)
    }
    if !self.audioChannels.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.audioChannels, fieldNumber: 6)
    }
    if !self.visions.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.visions, fieldNumber: 7)
    }
    if !self.automations.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.automations, fieldNumber: 8)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Ldtx_Workspace_V1_Workspace, rhs: Ldtx_Workspace_V1_Workspace) -> Bool {
    if lhs.id != rhs.id {return false}
    if lhs.name != rhs.name {return false}
    if lhs.programs != rhs.programs {return false}
    if lhs.programPreferences != rhs.programPreferences {return false}
    if lhs.inputDevices != rhs.inputDevices {return false}
    if lhs.audioChannels != rhs.audioChannels {return false}
    if lhs.visions != rhs.visions {return false}
    if lhs.automations != rhs.automations {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Ldtx_Workspace_V1_WorkspacePreferences: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".WorkspacePreferences"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}program_preferences\0\u{3}physical_device_ids_by_input_device_id\0\u{3}input_camera_device_mappings\0\u{3}input_audio_device_mappings\0\u{3}input_audio_monitor_channel_keys\0\u{3}selected_program_name\0\u{1}output\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.programPreferences) }()
      case 2: try { try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufString>.self, value: &self.physicalDeviceIdsByInputDeviceID) }()
      case 3: try { try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufString>.self, value: &self.inputCameraDeviceMappings) }()
      case 4: try { try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufString>.self, value: &self.inputAudioDeviceMappings) }()
      case 5: try { try decoder.decodeRepeatedStringField(value: &self.inputAudioMonitorChannelKeys) }()
      case 6: try { try decoder.decodeSingularStringField(value: &self._selectedProgramName) }()
      case 7: try { try decoder.decodeSingularMessageField(value: &self._output) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.programPreferences.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.programPreferences, fieldNumber: 1)
    }
    if !self.physicalDeviceIdsByInputDeviceID.isEmpty {
      try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufString>.self, value: self.physicalDeviceIdsByInputDeviceID, fieldNumber: 2)
    }
    if !self.inputCameraDeviceMappings.isEmpty {
      try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufString>.self, value: self.inputCameraDeviceMappings, fieldNumber: 3)
    }
    if !self.inputAudioDeviceMappings.isEmpty {
      try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufString>.self, value: self.inputAudioDeviceMappings, fieldNumber: 4)
    }
    if !self.inputAudioMonitorChannelKeys.isEmpty {
      try visitor.visitRepeatedStringField(value: self.inputAudioMonitorChannelKeys, fieldNumber: 5)
    }
    try { if let v = self._selectedProgramName {
      try visitor.visitSingularStringField(value: v, fieldNumber: 6)
    } }()
    try { if let v = self._output {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 7)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Ldtx_Workspace_V1_WorkspacePreferences, rhs: Ldtx_Workspace_V1_WorkspacePreferences) -> Bool {
    if lhs.programPreferences != rhs.programPreferences {return false}
    if lhs.physicalDeviceIdsByInputDeviceID != rhs.physicalDeviceIdsByInputDeviceID {return false}
    if lhs.inputCameraDeviceMappings != rhs.inputCameraDeviceMappings {return false}
    if lhs.inputAudioDeviceMappings != rhs.inputAudioDeviceMappings {return false}
    if lhs.inputAudioMonitorChannelKeys != rhs.inputAudioMonitorChannelKeys {return false}
    if lhs._selectedProgramName != rhs._selectedProgramName {return false}
    if lhs._output != rhs._output {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Ldtx_Workspace_V1_OutputPreferences: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".OutputPreferences"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}capture_output_mode\0\u{3}existing_broadcast_id\0\u{3}stream_title\0\u{3}stream_description\0\u{3}prefers_color_preview\0\u{3}local_output_base_directory_path\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.captureOutputMode) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.existingBroadcastID) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.streamTitle) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.streamDescription) }()
      case 5: try { try decoder.decodeSingularBoolField(value: &self.prefersColorPreview) }()
      case 6: try { try decoder.decodeSingularStringField(value: &self.localOutputBaseDirectoryPath) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.captureOutputMode.isEmpty {
      try visitor.visitSingularStringField(value: self.captureOutputMode, fieldNumber: 1)
    }
    if !self.existingBroadcastID.isEmpty {
      try visitor.visitSingularStringField(value: self.existingBroadcastID, fieldNumber: 2)
    }
    if !self.streamTitle.isEmpty {
      try visitor.visitSingularStringField(value: self.streamTitle, fieldNumber: 3)
    }
    if !self.streamDescription.isEmpty {
      try visitor.visitSingularStringField(value: self.streamDescription, fieldNumber: 4)
    }
    if self.prefersColorPreview != false {
      try visitor.visitSingularBoolField(value: self.prefersColorPreview, fieldNumber: 5)
    }
    if !self.localOutputBaseDirectoryPath.isEmpty {
      try visitor.visitSingularStringField(value: self.localOutputBaseDirectoryPath, fieldNumber: 6)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Ldtx_Workspace_V1_OutputPreferences, rhs: Ldtx_Workspace_V1_OutputPreferences) -> Bool {
    if lhs.captureOutputMode != rhs.captureOutputMode {return false}
    if lhs.existingBroadcastID != rhs.existingBroadcastID {return false}
    if lhs.streamTitle != rhs.streamTitle {return false}
    if lhs.streamDescription != rhs.streamDescription {return false}
    if lhs.prefersColorPreview != rhs.prefersColorPreview {return false}
    if lhs.localOutputBaseDirectoryPath != rhs.localOutputBaseDirectoryPath {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Ldtx_Workspace_V1_VisionRecord: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".VisionRecord"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}id\0\u{1}name\0\u{3}current_program_output\0\u{3}input_device_id\0\u{3}model_repository_id\0\u{3}model_revision\0\u{1}prompt\0\u{3}system_prompt\0\u{3}user_prompt\0\u{3}update_interval_seconds\0\u{3}stops_at_newline\0\u{3}post_action_automation_id\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.id) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.name) }()
      case 3: try {
        var v: Bool?
        try decoder.decodeSingularBoolField(value: &v)
        if let v = v {
          if self.source != nil {try decoder.handleConflictingOneOf()}
          self.source = .currentProgramOutput(v)
        }
      }()
      case 4: try {
        var v: String?
        try decoder.decodeSingularStringField(value: &v)
        if let v = v {
          if self.source != nil {try decoder.handleConflictingOneOf()}
          self.source = .inputDeviceID(v)
        }
      }()
      case 5: try { try decoder.decodeSingularStringField(value: &self.modelRepositoryID) }()
      case 6: try { try decoder.decodeSingularStringField(value: &self._modelRevision) }()
      case 7: try { try decoder.decodeSingularStringField(value: &self.prompt) }()
      case 8: try { try decoder.decodeSingularStringField(value: &self.systemPrompt) }()
      case 9: try { try decoder.decodeSingularStringField(value: &self.userPrompt) }()
      case 10: try { try decoder.decodeSingularDoubleField(value: &self.updateIntervalSeconds) }()
      case 11: try { try decoder.decodeSingularBoolField(value: &self.stopsAtNewline) }()
      case 12: try { try decoder.decodeSingularStringField(value: &self._postActionAutomationID) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.id.isEmpty {
      try visitor.visitSingularStringField(value: self.id, fieldNumber: 1)
    }
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 2)
    }
    switch self.source {
    case .currentProgramOutput?: try {
      guard case .currentProgramOutput(let v)? = self.source else { preconditionFailure() }
      try visitor.visitSingularBoolField(value: v, fieldNumber: 3)
    }()
    case .inputDeviceID?: try {
      guard case .inputDeviceID(let v)? = self.source else { preconditionFailure() }
      try visitor.visitSingularStringField(value: v, fieldNumber: 4)
    }()
    case nil: break
    }
    if !self.modelRepositoryID.isEmpty {
      try visitor.visitSingularStringField(value: self.modelRepositoryID, fieldNumber: 5)
    }
    try { if let v = self._modelRevision {
      try visitor.visitSingularStringField(value: v, fieldNumber: 6)
    } }()
    if !self.prompt.isEmpty {
      try visitor.visitSingularStringField(value: self.prompt, fieldNumber: 7)
    }
    if !self.systemPrompt.isEmpty {
      try visitor.visitSingularStringField(value: self.systemPrompt, fieldNumber: 8)
    }
    if !self.userPrompt.isEmpty {
      try visitor.visitSingularStringField(value: self.userPrompt, fieldNumber: 9)
    }
    if self.updateIntervalSeconds.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.updateIntervalSeconds, fieldNumber: 10)
    }
    if self.stopsAtNewline != false {
      try visitor.visitSingularBoolField(value: self.stopsAtNewline, fieldNumber: 11)
    }
    try { if let v = self._postActionAutomationID {
      try visitor.visitSingularStringField(value: v, fieldNumber: 12)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Ldtx_Workspace_V1_VisionRecord, rhs: Ldtx_Workspace_V1_VisionRecord) -> Bool {
    if lhs.id != rhs.id {return false}
    if lhs.name != rhs.name {return false}
    if lhs.source != rhs.source {return false}
    if lhs.modelRepositoryID != rhs.modelRepositoryID {return false}
    if lhs._modelRevision != rhs._modelRevision {return false}
    if lhs.prompt != rhs.prompt {return false}
    if lhs.systemPrompt != rhs.systemPrompt {return false}
    if lhs.userPrompt != rhs.userPrompt {return false}
    if lhs.updateIntervalSeconds != rhs.updateIntervalSeconds {return false}
    if lhs.stopsAtNewline != rhs.stopsAtNewline {return false}
    if lhs._postActionAutomationID != rhs._postActionAutomationID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Ldtx_Workspace_V1_AutomationRecord: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".AutomationRecord"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}id\0\u{1}name\0\u{3}is_enabled\0\u{1}trigger\0\u{1}actions\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.id) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.name) }()
      case 3: try { try decoder.decodeSingularBoolField(value: &self.isEnabled) }()
      case 4: try { try decoder.decodeSingularMessageField(value: &self._trigger) }()
      case 5: try { try decoder.decodeRepeatedMessageField(value: &self.actions) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.id.isEmpty {
      try visitor.visitSingularStringField(value: self.id, fieldNumber: 1)
    }
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 2)
    }
    if self.isEnabled != false {
      try visitor.visitSingularBoolField(value: self.isEnabled, fieldNumber: 3)
    }
    try { if let v = self._trigger {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
    } }()
    if !self.actions.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.actions, fieldNumber: 5)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Ldtx_Workspace_V1_AutomationRecord, rhs: Ldtx_Workspace_V1_AutomationRecord) -> Bool {
    if lhs.id != rhs.id {return false}
    if lhs.name != rhs.name {return false}
    if lhs.isEnabled != rhs.isEnabled {return false}
    if lhs._trigger != rhs._trigger {return false}
    if lhs.actions != rhs.actions {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Ldtx_Workspace_V1_AutomationTrigger: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".AutomationTrigger"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}manual\0\u{3}interval_seconds\0\u{3}vision_result_changed_id\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try {
        var v: Bool?
        try decoder.decodeSingularBoolField(value: &v)
        if let v = v {
          if self.definition != nil {try decoder.handleConflictingOneOf()}
          self.definition = .manual(v)
        }
      }()
      case 2: try {
        var v: Double?
        try decoder.decodeSingularDoubleField(value: &v)
        if let v = v {
          if self.definition != nil {try decoder.handleConflictingOneOf()}
          self.definition = .intervalSeconds(v)
        }
      }()
      case 3: try {
        var v: String?
        try decoder.decodeSingularStringField(value: &v)
        if let v = v {
          if self.definition != nil {try decoder.handleConflictingOneOf()}
          self.definition = .visionResultChangedID(v)
        }
      }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    switch self.definition {
    case .manual?: try {
      guard case .manual(let v)? = self.definition else { preconditionFailure() }
      try visitor.visitSingularBoolField(value: v, fieldNumber: 1)
    }()
    case .intervalSeconds?: try {
      guard case .intervalSeconds(let v)? = self.definition else { preconditionFailure() }
      try visitor.visitSingularDoubleField(value: v, fieldNumber: 2)
    }()
    case .visionResultChangedID?: try {
      guard case .visionResultChangedID(let v)? = self.definition else { preconditionFailure() }
      try visitor.visitSingularStringField(value: v, fieldNumber: 3)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Ldtx_Workspace_V1_AutomationTrigger, rhs: Ldtx_Workspace_V1_AutomationTrigger) -> Bool {
    if lhs.definition != rhs.definition {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Ldtx_Workspace_V1_AutomationAction: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".AutomationAction"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}id\0\u{3}analyze_vision_id\0\u{3}select_input_device_id\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.id) }()
      case 2: try {
        var v: String?
        try decoder.decodeSingularStringField(value: &v)
        if let v = v {
          if self.definition != nil {try decoder.handleConflictingOneOf()}
          self.definition = .analyzeVisionID(v)
        }
      }()
      case 3: try {
        var v: String?
        try decoder.decodeSingularStringField(value: &v)
        if let v = v {
          if self.definition != nil {try decoder.handleConflictingOneOf()}
          self.definition = .selectInputDeviceID(v)
        }
      }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.id.isEmpty {
      try visitor.visitSingularStringField(value: self.id, fieldNumber: 1)
    }
    switch self.definition {
    case .analyzeVisionID?: try {
      guard case .analyzeVisionID(let v)? = self.definition else { preconditionFailure() }
      try visitor.visitSingularStringField(value: v, fieldNumber: 2)
    }()
    case .selectInputDeviceID?: try {
      guard case .selectInputDeviceID(let v)? = self.definition else { preconditionFailure() }
      try visitor.visitSingularStringField(value: v, fieldNumber: 3)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Ldtx_Workspace_V1_AutomationAction, rhs: Ldtx_Workspace_V1_AutomationAction) -> Bool {
    if lhs.id != rhs.id {return false}
    if lhs.definition != rhs.definition {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Ldtx_Workspace_V1_ProgramRecord: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ProgramRecord"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}name\0\u{3}canvas_width\0\u{3}canvas_height\0\u{3}frame_rate_numerator\0\u{3}frame_rate_denominator\0\u{1}program\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.name) }()
      case 2: try { try decoder.decodeSingularUInt32Field(value: &self.canvasWidth) }()
      case 3: try { try decoder.decodeSingularUInt32Field(value: &self.canvasHeight) }()
      case 4: try { try decoder.decodeSingularUInt32Field(value: &self.frameRateNumerator) }()
      case 5: try { try decoder.decodeSingularUInt32Field(value: &self.frameRateDenominator) }()
      case 6: try { try decoder.decodeSingularMessageField(value: &self._program) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 1)
    }
    if self.canvasWidth != 0 {
      try visitor.visitSingularUInt32Field(value: self.canvasWidth, fieldNumber: 2)
    }
    if self.canvasHeight != 0 {
      try visitor.visitSingularUInt32Field(value: self.canvasHeight, fieldNumber: 3)
    }
    if self.frameRateNumerator != 0 {
      try visitor.visitSingularUInt32Field(value: self.frameRateNumerator, fieldNumber: 4)
    }
    if self.frameRateDenominator != 0 {
      try visitor.visitSingularUInt32Field(value: self.frameRateDenominator, fieldNumber: 5)
    }
    try { if let v = self._program {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 6)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Ldtx_Workspace_V1_ProgramRecord, rhs: Ldtx_Workspace_V1_ProgramRecord) -> Bool {
    if lhs.name != rhs.name {return false}
    if lhs.canvasWidth != rhs.canvasWidth {return false}
    if lhs.canvasHeight != rhs.canvasHeight {return false}
    if lhs.frameRateNumerator != rhs.frameRateNumerator {return false}
    if lhs.frameRateDenominator != rhs.frameRateDenominator {return false}
    if lhs._program != rhs._program {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Ldtx_Workspace_V1_ProgramPreferencesRecord: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ProgramPreferencesRecord"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}name\0\u{1}preferences\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.name) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._preferences) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 1)
    }
    try { if let v = self._preferences {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Ldtx_Workspace_V1_ProgramPreferencesRecord, rhs: Ldtx_Workspace_V1_ProgramPreferencesRecord) -> Bool {
    if lhs.name != rhs.name {return false}
    if lhs._preferences != rhs._preferences {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Ldtx_Workspace_V1_InputDeviceRecord: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".InputDeviceRecord"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}name\0\u{1}kind\0\u{3}side_track_recording_policy\0\u{1}id\0\u{3}physical_device_id\0\u{3}background_removal_policy\0\u{3}color_range_policy\0\u{3}capture_width_override\0\u{3}capture_height_override\0\u{3}capture_frame_rate_override\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.name) }()
      case 2: try { try decoder.decodeSingularEnumField(value: &self.kind) }()
      case 3: try { try decoder.decodeSingularEnumField(value: &self.sideTrackRecordingPolicy) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.id) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self.physicalDeviceID) }()
      case 6: try { try decoder.decodeSingularEnumField(value: &self.backgroundRemovalPolicy) }()
      case 7: try { try decoder.decodeSingularEnumField(value: &self.colorRangePolicy) }()
      case 8: try { try decoder.decodeSingularUInt32Field(value: &self.captureWidthOverride) }()
      case 9: try { try decoder.decodeSingularUInt32Field(value: &self.captureHeightOverride) }()
      case 10: try { try decoder.decodeSingularUInt32Field(value: &self.captureFrameRateOverride) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 1)
    }
    if self.kind != .unspecified {
      try visitor.visitSingularEnumField(value: self.kind, fieldNumber: 2)
    }
    if self.sideTrackRecordingPolicy != .unspecified {
      try visitor.visitSingularEnumField(value: self.sideTrackRecordingPolicy, fieldNumber: 3)
    }
    if !self.id.isEmpty {
      try visitor.visitSingularStringField(value: self.id, fieldNumber: 4)
    }
    if !self.physicalDeviceID.isEmpty {
      try visitor.visitSingularStringField(value: self.physicalDeviceID, fieldNumber: 5)
    }
    if self.backgroundRemovalPolicy != .unspecified {
      try visitor.visitSingularEnumField(value: self.backgroundRemovalPolicy, fieldNumber: 6)
    }
    if self.colorRangePolicy != .unspecified {
      try visitor.visitSingularEnumField(value: self.colorRangePolicy, fieldNumber: 7)
    }
    if self.captureWidthOverride != 0 {
      try visitor.visitSingularUInt32Field(value: self.captureWidthOverride, fieldNumber: 8)
    }
    if self.captureHeightOverride != 0 {
      try visitor.visitSingularUInt32Field(value: self.captureHeightOverride, fieldNumber: 9)
    }
    if self.captureFrameRateOverride != 0 {
      try visitor.visitSingularUInt32Field(value: self.captureFrameRateOverride, fieldNumber: 10)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Ldtx_Workspace_V1_InputDeviceRecord, rhs: Ldtx_Workspace_V1_InputDeviceRecord) -> Bool {
    if lhs.name != rhs.name {return false}
    if lhs.kind != rhs.kind {return false}
    if lhs.sideTrackRecordingPolicy != rhs.sideTrackRecordingPolicy {return false}
    if lhs.id != rhs.id {return false}
    if lhs.physicalDeviceID != rhs.physicalDeviceID {return false}
    if lhs.backgroundRemovalPolicy != rhs.backgroundRemovalPolicy {return false}
    if lhs.colorRangePolicy != rhs.colorRangePolicy {return false}
    if lhs.captureWidthOverride != rhs.captureWidthOverride {return false}
    if lhs.captureHeightOverride != rhs.captureHeightOverride {return false}
    if lhs.captureFrameRateOverride != rhs.captureFrameRateOverride {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
