// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: workspace_v4_preferences.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

// SPDX-FileCopyrightText: 2026 Kaito Udagawa <umireon@kaito.tokyo>
//
// SPDX-License-Identifier: Apache-2.0

/// Version 4 Workspace mutable preferences.

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// Contains mutable preferences for one WorkspaceDefinitionV4.
public nonisolated struct Ldtx_Workspace_V4_WorkspacePreferencesV4: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var audioChannelGainsDecibels: Dictionary<UInt64,Ldtx_Workspace_V4_Rational32> = [:]

  /// Preferences for each Landscape Program, keyed by Program internal_id.
  public var landscapeProgramPreferences: Dictionary<UInt64,Ldtx_Workspace_V4_ProgramPreferences> = [:]

  /// Preferences for each Portrait Program, keyed by Program internal_id.
  public var portraitProgramPreferences: Dictionary<UInt64,Ldtx_Workspace_V4_ProgramPreferences> = [:]

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// Contains mutable preferences for one Program canvas.
public nonisolated struct Ldtx_Workspace_V4_ProgramPreferences: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var audioMasterVolumeDecibels: Ldtx_Workspace_V4_Rational32 {
    get {_audioMasterVolumeDecibels ?? Ldtx_Workspace_V4_Rational32()}
    set {_audioMasterVolumeDecibels = newValue}
  }
  /// Returns true if `audioMasterVolumeDecibels` has been explicitly set.
  public var hasAudioMasterVolumeDecibels: Bool {self._audioMasterVolumeDecibels != nil}
  /// Clears the value of `audioMasterVolumeDecibels`. Subsequent reads from it will return its default value.
  public mutating func clearAudioMasterVolumeDecibels() {self._audioMasterVolumeDecibels = nil}

  /// Whether each Audio Input Device is muted, keyed by internal_id.
  public var audioChannelMuted: Dictionary<UInt64,Bool> = [:]

  /// Video Layer transforms, keyed by Video Component internal_id.
  public var videoLayerTransforms: Dictionary<UInt64,Ldtx_Workspace_V4_BasicTransform> = [:]

  /// Whether each Video Layer is hidden, keyed by internal_id.
  public var videoLayerHidden: Dictionary<UInt64,Bool> = [:]

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _audioMasterVolumeDecibels: Ldtx_Workspace_V4_Rational32? = nil
}

/// The basic transform applied to a Video Layer, which is a Video Component.
public nonisolated struct Ldtx_Workspace_V4_BasicTransform: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var translationXRational: Ldtx_Workspace_V4_Rational32 {
    get {_translationXRational ?? Ldtx_Workspace_V4_Rational32()}
    set {_translationXRational = newValue}
  }
  /// Returns true if `translationXRational` has been explicitly set.
  public var hasTranslationXRational: Bool {self._translationXRational != nil}
  /// Clears the value of `translationXRational`. Subsequent reads from it will return its default value.
  public mutating func clearTranslationXRational() {self._translationXRational = nil}

  public var translationYRational: Ldtx_Workspace_V4_Rational32 {
    get {_translationYRational ?? Ldtx_Workspace_V4_Rational32()}
    set {_translationYRational = newValue}
  }
  /// Returns true if `translationYRational` has been explicitly set.
  public var hasTranslationYRational: Bool {self._translationYRational != nil}
  /// Clears the value of `translationYRational`. Subsequent reads from it will return its default value.
  public mutating func clearTranslationYRational() {self._translationYRational = nil}

  public var scaleXRational: Ldtx_Workspace_V4_Rational32 {
    get {_scaleXRational ?? Ldtx_Workspace_V4_Rational32()}
    set {_scaleXRational = newValue}
  }
  /// Returns true if `scaleXRational` has been explicitly set.
  public var hasScaleXRational: Bool {self._scaleXRational != nil}
  /// Clears the value of `scaleXRational`. Subsequent reads from it will return its default value.
  public mutating func clearScaleXRational() {self._scaleXRational = nil}

  public var scaleYRational: Ldtx_Workspace_V4_Rational32 {
    get {_scaleYRational ?? Ldtx_Workspace_V4_Rational32()}
    set {_scaleYRational = newValue}
  }
  /// Returns true if `scaleYRational` has been explicitly set.
  public var hasScaleYRational: Bool {self._scaleYRational != nil}
  /// Clears the value of `scaleYRational`. Subsequent reads from it will return its default value.
  public mutating func clearScaleYRational() {self._scaleYRational = nil}

  public var topInsetRational: Ldtx_Workspace_V4_Rational32 {
    get {_topInsetRational ?? Ldtx_Workspace_V4_Rational32()}
    set {_topInsetRational = newValue}
  }
  /// Returns true if `topInsetRational` has been explicitly set.
  public var hasTopInsetRational: Bool {self._topInsetRational != nil}
  /// Clears the value of `topInsetRational`. Subsequent reads from it will return its default value.
  public mutating func clearTopInsetRational() {self._topInsetRational = nil}

  public var rightInsetRational: Ldtx_Workspace_V4_Rational32 {
    get {_rightInsetRational ?? Ldtx_Workspace_V4_Rational32()}
    set {_rightInsetRational = newValue}
  }
  /// Returns true if `rightInsetRational` has been explicitly set.
  public var hasRightInsetRational: Bool {self._rightInsetRational != nil}
  /// Clears the value of `rightInsetRational`. Subsequent reads from it will return its default value.
  public mutating func clearRightInsetRational() {self._rightInsetRational = nil}

  public var bottomInsetRational: Ldtx_Workspace_V4_Rational32 {
    get {_bottomInsetRational ?? Ldtx_Workspace_V4_Rational32()}
    set {_bottomInsetRational = newValue}
  }
  /// Returns true if `bottomInsetRational` has been explicitly set.
  public var hasBottomInsetRational: Bool {self._bottomInsetRational != nil}
  /// Clears the value of `bottomInsetRational`. Subsequent reads from it will return its default value.
  public mutating func clearBottomInsetRational() {self._bottomInsetRational = nil}

  public var leftInsetRational: Ldtx_Workspace_V4_Rational32 {
    get {_leftInsetRational ?? Ldtx_Workspace_V4_Rational32()}
    set {_leftInsetRational = newValue}
  }
  /// Returns true if `leftInsetRational` has been explicitly set.
  public var hasLeftInsetRational: Bool {self._leftInsetRational != nil}
  /// Clears the value of `leftInsetRational`. Subsequent reads from it will return its default value.
  public mutating func clearLeftInsetRational() {self._leftInsetRational = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _translationXRational: Ldtx_Workspace_V4_Rational32? = nil
  fileprivate var _translationYRational: Ldtx_Workspace_V4_Rational32? = nil
  fileprivate var _scaleXRational: Ldtx_Workspace_V4_Rational32? = nil
  fileprivate var _scaleYRational: Ldtx_Workspace_V4_Rational32? = nil
  fileprivate var _topInsetRational: Ldtx_Workspace_V4_Rational32? = nil
  fileprivate var _rightInsetRational: Ldtx_Workspace_V4_Rational32? = nil
  fileprivate var _bottomInsetRational: Ldtx_Workspace_V4_Rational32? = nil
  fileprivate var _leftInsetRational: Ldtx_Workspace_V4_Rational32? = nil
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "ldtx.workspace.v4"

nonisolated extension Ldtx_Workspace_V4_WorkspacePreferencesV4: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".WorkspacePreferencesV4"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{4}\u{2}landscape_program_preferences\0\u{3}portrait_program_preferences\0\u{3}audio_channel_gains_decibels\0\u{b}audio_channel_gains_decibel_tenths\0\u{c}\u{1}\u{1}")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 2: try { try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMessageMap<SwiftProtobuf.ProtobufUInt64,Ldtx_Workspace_V4_ProgramPreferences>.self, value: &self.landscapeProgramPreferences) }()
      case 3: try { try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMessageMap<SwiftProtobuf.ProtobufUInt64,Ldtx_Workspace_V4_ProgramPreferences>.self, value: &self.portraitProgramPreferences) }()
      case 4: try { try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMessageMap<SwiftProtobuf.ProtobufUInt64,Ldtx_Workspace_V4_Rational32>.self, value: &self.audioChannelGainsDecibels) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.landscapeProgramPreferences.isEmpty {
      try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMessageMap<SwiftProtobuf.ProtobufUInt64,Ldtx_Workspace_V4_ProgramPreferences>.self, value: self.landscapeProgramPreferences, fieldNumber: 2)
    }
    if !self.portraitProgramPreferences.isEmpty {
      try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMessageMap<SwiftProtobuf.ProtobufUInt64,Ldtx_Workspace_V4_ProgramPreferences>.self, value: self.portraitProgramPreferences, fieldNumber: 3)
    }
    if !self.audioChannelGainsDecibels.isEmpty {
      try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMessageMap<SwiftProtobuf.ProtobufUInt64,Ldtx_Workspace_V4_Rational32>.self, value: self.audioChannelGainsDecibels, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Ldtx_Workspace_V4_WorkspacePreferencesV4, rhs: Ldtx_Workspace_V4_WorkspacePreferencesV4) -> Bool {
    if lhs.audioChannelGainsDecibels != rhs.audioChannelGainsDecibels {return false}
    if lhs.landscapeProgramPreferences != rhs.landscapeProgramPreferences {return false}
    if lhs.portraitProgramPreferences != rhs.portraitProgramPreferences {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Ldtx_Workspace_V4_ProgramPreferences: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ProgramPreferences"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{4}\u{2}audio_channel_muted\0\u{3}video_layer_transforms\0\u{3}video_layer_hidden\0\u{3}audio_master_volume_decibels\0\u{b}audio_master_volume_decibel_tenths\0\u{c}\u{1}\u{1}")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 2: try { try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufUInt64,SwiftProtobuf.ProtobufBool>.self, value: &self.audioChannelMuted) }()
      case 3: try { try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMessageMap<SwiftProtobuf.ProtobufUInt64,Ldtx_Workspace_V4_BasicTransform>.self, value: &self.videoLayerTransforms) }()
      case 4: try { try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufUInt64,SwiftProtobuf.ProtobufBool>.self, value: &self.videoLayerHidden) }()
      case 5: try { try decoder.decodeSingularMessageField(value: &self._audioMasterVolumeDecibels) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.audioChannelMuted.isEmpty {
      try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufUInt64,SwiftProtobuf.ProtobufBool>.self, value: self.audioChannelMuted, fieldNumber: 2)
    }
    if !self.videoLayerTransforms.isEmpty {
      try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMessageMap<SwiftProtobuf.ProtobufUInt64,Ldtx_Workspace_V4_BasicTransform>.self, value: self.videoLayerTransforms, fieldNumber: 3)
    }
    if !self.videoLayerHidden.isEmpty {
      try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufUInt64,SwiftProtobuf.ProtobufBool>.self, value: self.videoLayerHidden, fieldNumber: 4)
    }
    try { if let v = self._audioMasterVolumeDecibels {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Ldtx_Workspace_V4_ProgramPreferences, rhs: Ldtx_Workspace_V4_ProgramPreferences) -> Bool {
    if lhs._audioMasterVolumeDecibels != rhs._audioMasterVolumeDecibels {return false}
    if lhs.audioChannelMuted != rhs.audioChannelMuted {return false}
    if lhs.videoLayerTransforms != rhs.videoLayerTransforms {return false}
    if lhs.videoLayerHidden != rhs.videoLayerHidden {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Ldtx_Workspace_V4_BasicTransform: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".BasicTransform"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{4}\u{9}translation_x_rational\0\u{3}translation_y_rational\0\u{3}scale_x_rational\0\u{3}scale_y_rational\0\u{3}top_inset_rational\0\u{3}right_inset_rational\0\u{3}bottom_inset_rational\0\u{3}left_inset_rational\0\u{b}translation_x\0\u{b}translation_y\0\u{b}scale_x\0\u{b}scale_y\0\u{b}top_inset\0\u{b}right_inset\0\u{b}bottom_inset\0\u{b}left_inset\0\u{c}\u{1}\u{1}\u{c}\u{2}\u{1}\u{c}\u{3}\u{1}\u{c}\u{4}\u{1}\u{c}\u{5}\u{1}\u{c}\u{6}\u{1}\u{c}\u{7}\u{1}\u{c}\u{8}\u{1}")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 9: try { try decoder.decodeSingularMessageField(value: &self._translationXRational) }()
      case 10: try { try decoder.decodeSingularMessageField(value: &self._translationYRational) }()
      case 11: try { try decoder.decodeSingularMessageField(value: &self._scaleXRational) }()
      case 12: try { try decoder.decodeSingularMessageField(value: &self._scaleYRational) }()
      case 13: try { try decoder.decodeSingularMessageField(value: &self._topInsetRational) }()
      case 14: try { try decoder.decodeSingularMessageField(value: &self._rightInsetRational) }()
      case 15: try { try decoder.decodeSingularMessageField(value: &self._bottomInsetRational) }()
      case 16: try { try decoder.decodeSingularMessageField(value: &self._leftInsetRational) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._translationXRational {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 9)
    } }()
    try { if let v = self._translationYRational {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 10)
    } }()
    try { if let v = self._scaleXRational {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 11)
    } }()
    try { if let v = self._scaleYRational {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 12)
    } }()
    try { if let v = self._topInsetRational {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 13)
    } }()
    try { if let v = self._rightInsetRational {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 14)
    } }()
    try { if let v = self._bottomInsetRational {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 15)
    } }()
    try { if let v = self._leftInsetRational {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 16)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Ldtx_Workspace_V4_BasicTransform, rhs: Ldtx_Workspace_V4_BasicTransform) -> Bool {
    if lhs._translationXRational != rhs._translationXRational {return false}
    if lhs._translationYRational != rhs._translationYRational {return false}
    if lhs._scaleXRational != rhs._scaleXRational {return false}
    if lhs._scaleYRational != rhs._scaleYRational {return false}
    if lhs._topInsetRational != rhs._topInsetRational {return false}
    if lhs._rightInsetRational != rhs._rightInsetRational {return false}
    if lhs._bottomInsetRational != rhs._bottomInsetRational {return false}
    if lhs._leftInsetRational != rhs._leftInsetRational {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
