// SPDX-FileCopyrightText: 2026 Kaito Udagawa <umireon@kaito.tokyo>
//
// SPDX-License-Identifier: Apache-2.0

edition = "2024";

package ldtx.workspace.v4;

import "workspace_v4_types.proto";

// Contains mutable preferences for one WorkspaceDefinitionV4.
message WorkspacePreferencesV4 {
  // Audio gain in decibels, keyed by each Audio Input Device's LDTXWorkspaceID.
  map<uint64, Rational32> audio_channel_gains_decibels = 1;
  // Preferences for each Landscape Program, keyed by the Program's LDTXWorkspaceID.
  map<uint64, ProgramPreferences> landscape_program_preferences = 2;
  // Preferences for each Portrait Program, keyed by the Program's LDTXWorkspaceID.
  map<uint64, ProgramPreferences> portrait_program_preferences = 3;
}

// Contains mutable preferences for one Program canvas.
message ProgramPreferences {
  // Master volume in decibels.
  Rational32 audio_master_volume_decibels = 1;
  // Whether each Audio Input Device is muted, keyed by its LDTXWorkspaceID.
  map<uint64, bool> audio_channel_muted = 2;
  // The Video Component LDTXWorkspaceIDs in back-to-front compositing order
  // for this Program canvas. The first entry is the backmost Video Layer;
  // the last entry is the frontmost Video Layer.
  repeated uint64 video_layer_internal_ids = 3;
  // Video Layer transforms, keyed by each Video Component's LDTXWorkspaceID.
  map<uint64, BasicTransform> video_layer_transforms = 4;
  // Whether each Video Layer is hidden, keyed by its Video Component's LDTXWorkspaceID.
  map<uint64, bool> video_layer_hidden = 5;
}

// The basic transform applied to a Video Layer, which is a Video Component.
message BasicTransform {
  // The horizontal translation, normalized by the target Canvas width,
  // in [0, 1]. Positive values move the Video Layer rightward.
  Rational32 translation_x = 1;
  // The vertical translation, normalized by the target Canvas height,
  // in [0, 1]. Positive values move the Video Layer downward.
  Rational32 translation_y = 2;
  // The horizontal size as a dimensionless multiple of the target Canvas width,
  // with no range restriction. Zero specifies zero width.
  Rational32DefaultOne scale_x = 3;
  // The vertical size as a dimensionless multiple of the target Canvas height,
  // with no range restriction. Zero specifies zero height.
  Rational32DefaultOne scale_y = 4;
  // The top inset as a fraction of this Video Layer's statically defined
  // content height, in the range [0, 1].
  Rational32 top_inset = 5;
  // The right inset as a fraction of this Video Layer's statically defined
  // content width, in the range [0, 1].
  Rational32 right_inset = 6;
  // The bottom inset as a fraction of this Video Layer's statically defined
  // content height, in the range [0, 1].
  Rational32 bottom_inset = 7;
  // The left inset as a fraction of this Video Layer's statically defined
  // content width, in the range [0, 1].
  Rational32 left_inset = 8;
}
