// SPDX-FileCopyrightText: 2026 Kaito Udagawa <umireon@kaito.tokyo>
//
// SPDX-License-Identifier: Apache-2.0

// Version 4 Workspace mutable preferences.
syntax = "proto3";

package ldtx.workspace.v4;

// Contains mutable preferences for one WorkspaceDefinitionV4.
message WorkspacePreferencesV4 {
  // Preferences for each Landscape Program, keyed by Program internal_id.
  map<uint64, ProgramPreferences> landscape_program_preferences = 1;
  // Preferences for each Portrait Program, keyed by Program internal_id.
  map<uint64, ProgramPreferences> portrait_program_preferences = 2;
}

// Contains mutable preferences for one Program canvas.
message ProgramPreferences {
  // Master volume in tenths of a decibel (-32 represents -3.2 dB).
  sint32 audio_master_volume_decibel_tenths = 1;
  // Audio gain in tenths of a decibel, keyed by Audio Input Device internal_id.
  map<uint64, sint32> audio_channel_gains_decibel_tenths = 2;
  // Whether each Audio Input Device is muted, keyed by internal_id.
  map<uint64, bool> audio_channel_muted = 3;
  // Video Layer transforms, keyed by Video Input Device or Component internal_id.
  map<uint64, BasicTransform> video_layer_transforms = 4;
  // Whether each Video Layer is hidden, keyed by internal_id.
  map<uint64, bool> video_layer_hidden = 5;
}

// The basic transform applied to a Video Layer, which is a Video Component.
message BasicTransform {
  // The horizontal translation in coordinates normalized to the Canvas that
  // renders this Video Layer, in the range [0, 1].
  float translation_x = 1;
  // The vertical translation in coordinates normalized to the Canvas that
  // renders this Video Layer, in the range [0, 1].
  float translation_y = 2;
  // The horizontal scale.
  float scale_x = 3;
  // The vertical scale.
  float scale_y = 4;
  // The top inset as a fraction of this Video Layer's statically defined
  // content height, in the range [0, 1].
  float top_inset = 5;
  // The right inset as a fraction of this Video Layer's statically defined
  // content width, in the range [0, 1].
  float right_inset = 6;
  // The bottom inset as a fraction of this Video Layer's statically defined
  // content height, in the range [0, 1].
  float bottom_inset = 7;
  // The left inset as a fraction of this Video Layer's statically defined
  // content width, in the range [0, 1].
  float left_inset = 8;
}
