// SPDX-FileCopyrightText: 2026 Kaito Udagawa <umireon@kaito.tokyo>
//
// SPDX-License-Identifier: Apache-2.0

edition = "2024";

package ldtx.workspace.v4;

import "workspace_v4_input_device.proto";
import "workspace_v4_video_component.proto";
import "workspace_v4_vision.proto";

// Version 4 WorkspaceDefinition.
message WorkspaceDefinitionV4 {
  // The title of this Workspace.
  string display_name = 1;
  // The Programs defined in this Workspace.
  repeated ProgramDefinition programs = 2;
  // Represents Canvas in the Workspace sidebar.
  CanvasConfiguration canvas_configuration = 3;
  // Represents Audio devices in the Workspace sidebar.
  repeated AudioInputDevice audio_devices = 5;
  // Represents Video Components in the Workspace sidebar.
  repeated VideoComponentWrapper video_components = 6;
  // Represents Visions in the Workspace sidebar.
  repeated VisionWrapper visions = 7;
}

// Defines the identity and display name of one Program.
message ProgramDefinition {
  // An LDTXWorkspaceID for this entity.
  uint64 internal_id = 1;
  // The name of this Program shown on the selector.
  string display_name = 2;
}

// Represents Canvas in the Workspace sidebar.
message CanvasConfiguration {
  // The profile identifier selected for the Landscape Canvas.
  string landscape_profile_id = 1;
  // The profile identifier selected for the Portrait Canvas.
  string portrait_profile_id = 2;
  // The output frame rate in frames per second.
  uint32 frame_rate = 3;
  // The target video bit rate for the Landscape Canvas in bits per second.
  uint32 landscape_video_bit_rate = 4;
  // The target video bit rate for the Portrait Canvas in bits per second.
  uint32 portrait_video_bit_rate = 5;
  // The LDTXWorkspaceID of the VFX Source used as the master clock for video
  // presentation timestamps.
  uint64 pts_master_vfx_source_internal_id = 6;
}
