// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: automation.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

// SPDX-FileCopyrightText: 2026 Kaito Udagawa <umireon@kaito.tokyo>
//
// SPDX-License-Identifier: Apache-2.0

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public nonisolated enum Ldtx_Automation_V1_CaptureOutputMode: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case unspecified // = 0
  case youtube // = 1
  case record // = 2
  case youtubeAndRecord // = 3
  case UNRECOGNIZED(Int)

  public init() {
    self = .unspecified
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .youtube
    case 2: self = .record
    case 3: self = .youtubeAndRecord
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .youtube: return 1
    case .record: return 2
    case .youtubeAndRecord: return 3
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [Ldtx_Automation_V1_CaptureOutputMode] = [
    .unspecified,
    .youtube,
    .record,
    .youtubeAndRecord,
  ]

}

public nonisolated enum Ldtx_Automation_V1_BroadcastSourceMode: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case unspecified // = 0
  case createNew // = 1
  case useExisting // = 2
  case UNRECOGNIZED(Int)

  public init() {
    self = .unspecified
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .createNew
    case 2: self = .useExisting
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .createNew: return 1
    case .useExisting: return 2
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [Ldtx_Automation_V1_BroadcastSourceMode] = [
    .unspecified,
    .createNew,
    .useExisting,
  ]

}

public nonisolated enum Ldtx_Automation_V1_YouTubeLiveStreamResolution: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case unspecified // = 0
  case p240 // = 1
  case p360 // = 2
  case p480 // = 3
  case p720 // = 4
  case p1080 // = 5
  case p1440 // = 6
  case p2160 // = 7
  case UNRECOGNIZED(Int)

  public init() {
    self = .unspecified
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .p240
    case 2: self = .p360
    case 3: self = .p480
    case 4: self = .p720
    case 5: self = .p1080
    case 6: self = .p1440
    case 7: self = .p2160
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .p240: return 1
    case .p360: return 2
    case .p480: return 3
    case .p720: return 4
    case .p1080: return 5
    case .p1440: return 6
    case .p2160: return 7
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [Ldtx_Automation_V1_YouTubeLiveStreamResolution] = [
    .unspecified,
    .p240,
    .p360,
    .p480,
    .p720,
    .p1080,
    .p1440,
    .p2160,
  ]

}

public nonisolated enum Ldtx_Automation_V1_YouTubeLiveStreamFrameRate: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case unspecified // = 0
  case fps30 // = 1
  case fps60 // = 2
  case UNRECOGNIZED(Int)

  public init() {
    self = .unspecified
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .fps30
    case 2: self = .fps60
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .fps30: return 1
    case .fps60: return 2
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [Ldtx_Automation_V1_YouTubeLiveStreamFrameRate] = [
    .unspecified,
    .fps30,
    .fps60,
  ]

}

public nonisolated enum Ldtx_Automation_V1_YouTubeLiveBroadcastPrivacyStatus: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case unspecified // = 0
  case `private` // = 1
  case unlisted // = 2
  case `public` // = 3
  case UNRECOGNIZED(Int)

  public init() {
    self = .unspecified
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .private
    case 2: self = .unlisted
    case 3: self = .public
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .private: return 1
    case .unlisted: return 2
    case .public: return 3
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [Ldtx_Automation_V1_YouTubeLiveBroadcastPrivacyStatus] = [
    .unspecified,
    .private,
    .unlisted,
    .public,
  ]

}

public nonisolated enum Ldtx_Automation_V1_YouTubeLiveBroadcastLatencyPreference: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case unspecified // = 0
  case normal // = 1
  case low // = 2
  case ultraLow // = 3
  case UNRECOGNIZED(Int)

  public init() {
    self = .unspecified
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .normal
    case 2: self = .low
    case 3: self = .ultraLow
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .normal: return 1
    case .low: return 2
    case .ultraLow: return 3
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [Ldtx_Automation_V1_YouTubeLiveBroadcastLatencyPreference] = [
    .unspecified,
    .normal,
    .low,
    .ultraLow,
  ]

}

public nonisolated struct Ldtx_Automation_V1_SelectedProgramNameResult: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var name: String = String()

  public var isScratchPad: Bool = false

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public nonisolated struct Ldtx_Automation_V1_ProgramSelectParams: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var name: String = String()

  public var isScratchPad: Bool = false

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public nonisolated struct Ldtx_Automation_V1_OutputSettings: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var captureOutputMode: Ldtx_Automation_V1_CaptureOutputMode {
    get {_captureOutputMode ?? .unspecified}
    set {_captureOutputMode = newValue}
  }
  /// Returns true if `captureOutputMode` has been explicitly set.
  public var hasCaptureOutputMode: Bool {self._captureOutputMode != nil}
  /// Clears the value of `captureOutputMode`. Subsequent reads from it will return its default value.
  public mutating func clearCaptureOutputMode() {self._captureOutputMode = nil}

  public var youtube: Ldtx_Automation_V1_YouTubeOutputSettings {
    get {_youtube ?? Ldtx_Automation_V1_YouTubeOutputSettings()}
    set {_youtube = newValue}
  }
  /// Returns true if `youtube` has been explicitly set.
  public var hasYoutube: Bool {self._youtube != nil}
  /// Clears the value of `youtube`. Subsequent reads from it will return its default value.
  public mutating func clearYoutube() {self._youtube = nil}

  public var recording: Ldtx_Automation_V1_RecordingOutputSettings {
    get {_recording ?? Ldtx_Automation_V1_RecordingOutputSettings()}
    set {_recording = newValue}
  }
  /// Returns true if `recording` has been explicitly set.
  public var hasRecording: Bool {self._recording != nil}
  /// Clears the value of `recording`. Subsequent reads from it will return its default value.
  public mutating func clearRecording() {self._recording = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _captureOutputMode: Ldtx_Automation_V1_CaptureOutputMode? = nil
  fileprivate var _youtube: Ldtx_Automation_V1_YouTubeOutputSettings? = nil
  fileprivate var _recording: Ldtx_Automation_V1_RecordingOutputSettings? = nil
}

public nonisolated struct Ldtx_Automation_V1_YouTubeOutputSettings: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var broadcastSourceMode: Ldtx_Automation_V1_BroadcastSourceMode {
    get {_broadcastSourceMode ?? .unspecified}
    set {_broadcastSourceMode = newValue}
  }
  /// Returns true if `broadcastSourceMode` has been explicitly set.
  public var hasBroadcastSourceMode: Bool {self._broadcastSourceMode != nil}
  /// Clears the value of `broadcastSourceMode`. Subsequent reads from it will return its default value.
  public mutating func clearBroadcastSourceMode() {self._broadcastSourceMode = nil}

  public var title: String {
    get {_title ?? String()}
    set {_title = newValue}
  }
  /// Returns true if `title` has been explicitly set.
  public var hasTitle: Bool {self._title != nil}
  /// Clears the value of `title`. Subsequent reads from it will return its default value.
  public mutating func clearTitle() {self._title = nil}

  public var description_p: String {
    get {_description_p ?? String()}
    set {_description_p = newValue}
  }
  /// Returns true if `description_p` has been explicitly set.
  public var hasDescription_p: Bool {self._description_p != nil}
  /// Clears the value of `description_p`. Subsequent reads from it will return its default value.
  public mutating func clearDescription_p() {self._description_p = nil}

  public var resolution: Ldtx_Automation_V1_YouTubeLiveStreamResolution {
    get {_resolution ?? .unspecified}
    set {_resolution = newValue}
  }
  /// Returns true if `resolution` has been explicitly set.
  public var hasResolution: Bool {self._resolution != nil}
  /// Clears the value of `resolution`. Subsequent reads from it will return its default value.
  public mutating func clearResolution() {self._resolution = nil}

  public var frameRate: Ldtx_Automation_V1_YouTubeLiveStreamFrameRate {
    get {_frameRate ?? .unspecified}
    set {_frameRate = newValue}
  }
  /// Returns true if `frameRate` has been explicitly set.
  public var hasFrameRate: Bool {self._frameRate != nil}
  /// Clears the value of `frameRate`. Subsequent reads from it will return its default value.
  public mutating func clearFrameRate() {self._frameRate = nil}

  public var usesTemporaryStream: Bool {
    get {_usesTemporaryStream ?? false}
    set {_usesTemporaryStream = newValue}
  }
  /// Returns true if `usesTemporaryStream` has been explicitly set.
  public var hasUsesTemporaryStream: Bool {self._usesTemporaryStream != nil}
  /// Clears the value of `usesTemporaryStream`. Subsequent reads from it will return its default value.
  public mutating func clearUsesTemporaryStream() {self._usesTemporaryStream = nil}

  public var existingBroadcastID: String {
    get {_existingBroadcastID ?? String()}
    set {_existingBroadcastID = newValue}
  }
  /// Returns true if `existingBroadcastID` has been explicitly set.
  public var hasExistingBroadcastID: Bool {self._existingBroadcastID != nil}
  /// Clears the value of `existingBroadcastID`. Subsequent reads from it will return its default value.
  public mutating func clearExistingBroadcastID() {self._existingBroadcastID = nil}

  public var privacyStatus: Ldtx_Automation_V1_YouTubeLiveBroadcastPrivacyStatus {
    get {_privacyStatus ?? .unspecified}
    set {_privacyStatus = newValue}
  }
  /// Returns true if `privacyStatus` has been explicitly set.
  public var hasPrivacyStatus: Bool {self._privacyStatus != nil}
  /// Clears the value of `privacyStatus`. Subsequent reads from it will return its default value.
  public mutating func clearPrivacyStatus() {self._privacyStatus = nil}

  public var latencyPreference: Ldtx_Automation_V1_YouTubeLiveBroadcastLatencyPreference {
    get {_latencyPreference ?? .unspecified}
    set {_latencyPreference = newValue}
  }
  /// Returns true if `latencyPreference` has been explicitly set.
  public var hasLatencyPreference: Bool {self._latencyPreference != nil}
  /// Clears the value of `latencyPreference`. Subsequent reads from it will return its default value.
  public mutating func clearLatencyPreference() {self._latencyPreference = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _broadcastSourceMode: Ldtx_Automation_V1_BroadcastSourceMode? = nil
  fileprivate var _title: String? = nil
  fileprivate var _description_p: String? = nil
  fileprivate var _resolution: Ldtx_Automation_V1_YouTubeLiveStreamResolution? = nil
  fileprivate var _frameRate: Ldtx_Automation_V1_YouTubeLiveStreamFrameRate? = nil
  fileprivate var _usesTemporaryStream: Bool? = nil
  fileprivate var _existingBroadcastID: String? = nil
  fileprivate var _privacyStatus: Ldtx_Automation_V1_YouTubeLiveBroadcastPrivacyStatus? = nil
  fileprivate var _latencyPreference: Ldtx_Automation_V1_YouTubeLiveBroadcastLatencyPreference? = nil
}

public nonisolated struct Ldtx_Automation_V1_RecordingOutputSettings: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var baseDirectoryPath: String {
    get {_baseDirectoryPath ?? String()}
    set {_baseDirectoryPath = newValue}
  }
  /// Returns true if `baseDirectoryPath` has been explicitly set.
  public var hasBaseDirectoryPath: Bool {self._baseDirectoryPath != nil}
  /// Clears the value of `baseDirectoryPath`. Subsequent reads from it will return its default value.
  public mutating func clearBaseDirectoryPath() {self._baseDirectoryPath = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _baseDirectoryPath: String? = nil
}

public nonisolated struct Ldtx_Automation_V1_CommandResult: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var ok: Bool = false

  public var message: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "ldtx.automation.v1"

nonisolated extension Ldtx_Automation_V1_CaptureOutputMode: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0CAPTURE_OUTPUT_MODE_UNSPECIFIED\0\u{1}CAPTURE_OUTPUT_MODE_YOUTUBE\0\u{1}CAPTURE_OUTPUT_MODE_RECORD\0\u{1}CAPTURE_OUTPUT_MODE_YOUTUBE_AND_RECORD\0")
}

nonisolated extension Ldtx_Automation_V1_BroadcastSourceMode: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0BROADCAST_SOURCE_MODE_UNSPECIFIED\0\u{1}BROADCAST_SOURCE_MODE_CREATE_NEW\0\u{1}BROADCAST_SOURCE_MODE_USE_EXISTING\0")
}

nonisolated extension Ldtx_Automation_V1_YouTubeLiveStreamResolution: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0YOUTUBE_LIVE_STREAM_RESOLUTION_UNSPECIFIED\0\u{1}YOUTUBE_LIVE_STREAM_RESOLUTION_P240\0\u{1}YOUTUBE_LIVE_STREAM_RESOLUTION_P360\0\u{1}YOUTUBE_LIVE_STREAM_RESOLUTION_P480\0\u{1}YOUTUBE_LIVE_STREAM_RESOLUTION_P720\0\u{1}YOUTUBE_LIVE_STREAM_RESOLUTION_P1080\0\u{1}YOUTUBE_LIVE_STREAM_RESOLUTION_P1440\0\u{1}YOUTUBE_LIVE_STREAM_RESOLUTION_P2160\0")
}

nonisolated extension Ldtx_Automation_V1_YouTubeLiveStreamFrameRate: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0YOUTUBE_LIVE_STREAM_FRAME_RATE_UNSPECIFIED\0\u{1}YOUTUBE_LIVE_STREAM_FRAME_RATE_FPS30\0\u{1}YOUTUBE_LIVE_STREAM_FRAME_RATE_FPS60\0")
}

nonisolated extension Ldtx_Automation_V1_YouTubeLiveBroadcastPrivacyStatus: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0YOUTUBE_LIVE_BROADCAST_PRIVACY_STATUS_UNSPECIFIED\0\u{1}YOUTUBE_LIVE_BROADCAST_PRIVACY_STATUS_PRIVATE\0\u{1}YOUTUBE_LIVE_BROADCAST_PRIVACY_STATUS_UNLISTED\0\u{1}YOUTUBE_LIVE_BROADCAST_PRIVACY_STATUS_PUBLIC\0")
}

nonisolated extension Ldtx_Automation_V1_YouTubeLiveBroadcastLatencyPreference: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0YOUTUBE_LIVE_BROADCAST_LATENCY_PREFERENCE_UNSPECIFIED\0\u{1}YOUTUBE_LIVE_BROADCAST_LATENCY_PREFERENCE_NORMAL\0\u{1}YOUTUBE_LIVE_BROADCAST_LATENCY_PREFERENCE_LOW\0\u{1}YOUTUBE_LIVE_BROADCAST_LATENCY_PREFERENCE_ULTRA_LOW\0")
}

nonisolated extension Ldtx_Automation_V1_SelectedProgramNameResult: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".SelectedProgramNameResult"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}name\0\u{3}is_scratch_pad\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.name) }()
      case 2: try { try decoder.decodeSingularBoolField(value: &self.isScratchPad) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 1)
    }
    if self.isScratchPad != false {
      try visitor.visitSingularBoolField(value: self.isScratchPad, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Ldtx_Automation_V1_SelectedProgramNameResult, rhs: Ldtx_Automation_V1_SelectedProgramNameResult) -> Bool {
    if lhs.name != rhs.name {return false}
    if lhs.isScratchPad != rhs.isScratchPad {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Ldtx_Automation_V1_ProgramSelectParams: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ProgramSelectParams"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}name\0\u{3}is_scratch_pad\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.name) }()
      case 2: try { try decoder.decodeSingularBoolField(value: &self.isScratchPad) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 1)
    }
    if self.isScratchPad != false {
      try visitor.visitSingularBoolField(value: self.isScratchPad, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Ldtx_Automation_V1_ProgramSelectParams, rhs: Ldtx_Automation_V1_ProgramSelectParams) -> Bool {
    if lhs.name != rhs.name {return false}
    if lhs.isScratchPad != rhs.isScratchPad {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Ldtx_Automation_V1_OutputSettings: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".OutputSettings"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}capture_output_mode\0\u{1}youtube\0\u{1}recording\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self._captureOutputMode) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._youtube) }()
      case 3: try { try decoder.decodeSingularMessageField(value: &self._recording) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._captureOutputMode {
      try visitor.visitSingularEnumField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._youtube {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._recording {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Ldtx_Automation_V1_OutputSettings, rhs: Ldtx_Automation_V1_OutputSettings) -> Bool {
    if lhs._captureOutputMode != rhs._captureOutputMode {return false}
    if lhs._youtube != rhs._youtube {return false}
    if lhs._recording != rhs._recording {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Ldtx_Automation_V1_YouTubeOutputSettings: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".YouTubeOutputSettings"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}broadcast_source_mode\0\u{1}title\0\u{1}description\0\u{1}resolution\0\u{3}frame_rate\0\u{3}uses_temporary_stream\0\u{3}existing_broadcast_id\0\u{3}privacy_status\0\u{3}latency_preference\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self._broadcastSourceMode) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self._title) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self._description_p) }()
      case 4: try { try decoder.decodeSingularEnumField(value: &self._resolution) }()
      case 5: try { try decoder.decodeSingularEnumField(value: &self._frameRate) }()
      case 6: try { try decoder.decodeSingularBoolField(value: &self._usesTemporaryStream) }()
      case 7: try { try decoder.decodeSingularStringField(value: &self._existingBroadcastID) }()
      case 8: try { try decoder.decodeSingularEnumField(value: &self._privacyStatus) }()
      case 9: try { try decoder.decodeSingularEnumField(value: &self._latencyPreference) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._broadcastSourceMode {
      try visitor.visitSingularEnumField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._title {
      try visitor.visitSingularStringField(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._description_p {
      try visitor.visitSingularStringField(value: v, fieldNumber: 3)
    } }()
    try { if let v = self._resolution {
      try visitor.visitSingularEnumField(value: v, fieldNumber: 4)
    } }()
    try { if let v = self._frameRate {
      try visitor.visitSingularEnumField(value: v, fieldNumber: 5)
    } }()
    try { if let v = self._usesTemporaryStream {
      try visitor.visitSingularBoolField(value: v, fieldNumber: 6)
    } }()
    try { if let v = self._existingBroadcastID {
      try visitor.visitSingularStringField(value: v, fieldNumber: 7)
    } }()
    try { if let v = self._privacyStatus {
      try visitor.visitSingularEnumField(value: v, fieldNumber: 8)
    } }()
    try { if let v = self._latencyPreference {
      try visitor.visitSingularEnumField(value: v, fieldNumber: 9)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Ldtx_Automation_V1_YouTubeOutputSettings, rhs: Ldtx_Automation_V1_YouTubeOutputSettings) -> Bool {
    if lhs._broadcastSourceMode != rhs._broadcastSourceMode {return false}
    if lhs._title != rhs._title {return false}
    if lhs._description_p != rhs._description_p {return false}
    if lhs._resolution != rhs._resolution {return false}
    if lhs._frameRate != rhs._frameRate {return false}
    if lhs._usesTemporaryStream != rhs._usesTemporaryStream {return false}
    if lhs._existingBroadcastID != rhs._existingBroadcastID {return false}
    if lhs._privacyStatus != rhs._privacyStatus {return false}
    if lhs._latencyPreference != rhs._latencyPreference {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Ldtx_Automation_V1_RecordingOutputSettings: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".RecordingOutputSettings"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}base_directory_path\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self._baseDirectoryPath) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._baseDirectoryPath {
      try visitor.visitSingularStringField(value: v, fieldNumber: 1)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Ldtx_Automation_V1_RecordingOutputSettings, rhs: Ldtx_Automation_V1_RecordingOutputSettings) -> Bool {
    if lhs._baseDirectoryPath != rhs._baseDirectoryPath {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Ldtx_Automation_V1_CommandResult: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".CommandResult"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}ok\0\u{1}message\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBoolField(value: &self.ok) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.message) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.ok != false {
      try visitor.visitSingularBoolField(value: self.ok, fieldNumber: 1)
    }
    if !self.message.isEmpty {
      try visitor.visitSingularStringField(value: self.message, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Ldtx_Automation_V1_CommandResult, rhs: Ldtx_Automation_V1_CommandResult) -> Bool {
    if lhs.ok != rhs.ok {return false}
    if lhs.message != rhs.message {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
