# SPDX-FileCopyrightText: 2026 Kaito Udagawa <umireon@kaito.tokyo>
#
# SPDX-License-Identifier: Apache-2.0

targets:
  LDTXYouTubeOutputServiceProcess:
    type: xpc-service
    platform: macOS
    sources:
      - Sources/LDTXYouTubeOutputServiceProcess
    info:
      path: Sources/LDTXYouTubeOutputServiceProcess/Info.plist
      properties:
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        XPCService:
          ServiceType: Application
    dependencies:
      - target: LDTXDash
        embed: true
        codeSign: true
      - target: LDTXDiagnostics
        embed: true
        codeSign: true
      - target: LDTXMP4
        embed: true
        codeSign: true
      - target: LDTXTaskQueue
        embed: true
        codeSign: true
      - target: LDTXYouTubeOutputProtocol
        embed: true
        codeSign: true
      - package: SwiftProtobuf
        product: SwiftProtobuf
        embed: false
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: tokyo.kaito.ldtx.LDTX.YouTubeOutputServiceProcess
        PRODUCT_NAME: LDTXYouTubeOutputServiceProcess
        SKIP_INSTALL: "YES"
        SWIFT_OBJC_INTEROP_MODE: objcxx
        CLANG_CXX_LANGUAGE_STANDARD: c++20
        ENABLE_HARDENED_RUNTIME: "YES"
  LDTXHelper:
    type: tool
    platform: macOS
    sources:
      - Sources/LDTXCLI/CLIEntryPoint.swift
    dependencies:
      - target: LDTXCLI
        embed: true
        codeSign: true
      - target: LDTXAppHelper
        embed: true
        codeSign: true
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: tokyo.kaito.ldtx.LDTX.Helper
        PRODUCT_NAME: LDTXHelper
        PRODUCT_MODULE_NAME: LDTXHelper
        GENERATE_INFOPLIST_FILE: YES
        CREATE_INFOPLIST_SECTION_IN_BINARY: YES
        SKIP_INSTALL: YES
        SWIFT_OBJC_INTEROP_MODE: objcxx
        CLANG_CXX_LANGUAGE_STANDARD: c++20
        ENABLE_HARDENED_RUNTIME: YES
        SWIFT_INCLUDE_PATHS: "$(inherited) $(BUILT_PRODUCTS_DIR)/ldtx-cli.framework/Modules"
        OTHER_SWIFT_FLAGS: "$(inherited) -parse-as-library"
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path @executable_path/PackageFrameworks @executable_path/../../Frameworks"
