// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: Sources/LDTXRecordingXPCProtocol/Protos/recording_xpc.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

// SPDX-FileCopyrightText: 2026 Kaito Udagawa <umireon@kaito.tokyo>
//
// SPDX-License-Identifier: Apache-2.0

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

nonisolated struct Ldtx_Recording_Xpc_V1_Context: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var sessionID: String = String()

  var generation: UInt64 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

nonisolated struct Ldtx_Recording_Xpc_V1_ConfigureRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var protocolVersion: UInt32 = 0

  var context: Ldtx_Recording_Xpc_V1_Context {
    get {_context ?? Ldtx_Recording_Xpc_V1_Context()}
    set {_context = newValue}
  }
  /// Returns true if `context` has been explicitly set.
  var hasContext: Bool {self._context != nil}
  /// Clears the value of `context`. Subsequent reads from it will return its default value.
  mutating func clearContext() {self._context = nil}

  var trackID: String = String()

  var ringCapacity: UInt64 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _context: Ldtx_Recording_Xpc_V1_Context? = nil
}

nonisolated struct Ldtx_Recording_Xpc_V1_CutRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var context: Ldtx_Recording_Xpc_V1_Context {
    get {_context ?? Ldtx_Recording_Xpc_V1_Context()}
    set {_context = newValue}
  }
  /// Returns true if `context` has been explicitly set.
  var hasContext: Bool {self._context != nil}
  /// Clears the value of `context`. Subsequent reads from it will return its default value.
  mutating func clearContext() {self._context = nil}

  var cutID: String = String()

  var presentationValue: Int64 = 0

  var presentationTimescale: Int32 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _context: Ldtx_Recording_Xpc_V1_Context? = nil
}

nonisolated struct Ldtx_Recording_Xpc_V1_FinishRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var context: Ldtx_Recording_Xpc_V1_Context {
    get {_context ?? Ldtx_Recording_Xpc_V1_Context()}
    set {_context = newValue}
  }
  /// Returns true if `context` has been explicitly set.
  var hasContext: Bool {self._context != nil}
  /// Clears the value of `context`. Subsequent reads from it will return its default value.
  mutating func clearContext() {self._context = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _context: Ldtx_Recording_Xpc_V1_Context? = nil
}

nonisolated struct Ldtx_Recording_Xpc_V1_Reply: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var accepted: Bool = false

  var errorMessage: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

nonisolated struct Ldtx_Recording_Xpc_V1_Event: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var context: Ldtx_Recording_Xpc_V1_Context {
    get {_context ?? Ldtx_Recording_Xpc_V1_Context()}
    set {_context = newValue}
  }
  /// Returns true if `context` has been explicitly set.
  var hasContext: Bool {self._context != nil}
  /// Clears the value of `context`. Subsequent reads from it will return its default value.
  mutating func clearContext() {self._context = nil}

  var kind: Ldtx_Recording_Xpc_V1_Event.Kind = .unspecified

  var trackID: String = String()

  var byteOffset: UInt64 = 0

  var byteLength: UInt64 = 0

  var presentationValue: Int64 = 0

  var presentationTimescale: Int32 = 0

  var durationValue: Int64 = 0

  var durationTimescale: Int32 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  nonisolated enum Kind: SwiftProtobuf.Enum, Swift.CaseIterable {
    typealias RawValue = Int
    case unspecified // = 0
    case prepared // = 1
    case fragmentCommitted // = 2
    case generationFinished // = 3
    case failed // = 4
    case recovered // = 5
    case UNRECOGNIZED(Int)

    init() {
      self = .unspecified
    }

    init?(rawValue: Int) {
      switch rawValue {
      case 0: self = .unspecified
      case 1: self = .prepared
      case 2: self = .fragmentCommitted
      case 3: self = .generationFinished
      case 4: self = .failed
      case 5: self = .recovered
      default: self = .UNRECOGNIZED(rawValue)
      }
    }

    var rawValue: Int {
      switch self {
      case .unspecified: return 0
      case .prepared: return 1
      case .fragmentCommitted: return 2
      case .generationFinished: return 3
      case .failed: return 4
      case .recovered: return 5
      case .UNRECOGNIZED(let i): return i
      }
    }

    // The compiler won't synthesize support with the UNRECOGNIZED case.
    static let allCases: [Ldtx_Recording_Xpc_V1_Event.Kind] = [
      .unspecified,
      .prepared,
      .fragmentCommitted,
      .generationFinished,
      .failed,
      .recovered,
    ]

  }

  init() {}

  fileprivate var _context: Ldtx_Recording_Xpc_V1_Context? = nil
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "ldtx.recording.xpc.v1"

nonisolated extension Ldtx_Recording_Xpc_V1_Context: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".Context"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}session_id\0\u{1}generation\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.sessionID) }()
      case 2: try { try decoder.decodeSingularUInt64Field(value: &self.generation) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.sessionID.isEmpty {
      try visitor.visitSingularStringField(value: self.sessionID, fieldNumber: 1)
    }
    if self.generation != 0 {
      try visitor.visitSingularUInt64Field(value: self.generation, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Ldtx_Recording_Xpc_V1_Context, rhs: Ldtx_Recording_Xpc_V1_Context) -> Bool {
    if lhs.sessionID != rhs.sessionID {return false}
    if lhs.generation != rhs.generation {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Ldtx_Recording_Xpc_V1_ConfigureRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".ConfigureRequest"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}protocol_version\0\u{1}context\0\u{3}track_id\0\u{3}ring_capacity\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt32Field(value: &self.protocolVersion) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._context) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.trackID) }()
      case 4: try { try decoder.decodeSingularUInt64Field(value: &self.ringCapacity) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.protocolVersion != 0 {
      try visitor.visitSingularUInt32Field(value: self.protocolVersion, fieldNumber: 1)
    }
    try { if let v = self._context {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    if !self.trackID.isEmpty {
      try visitor.visitSingularStringField(value: self.trackID, fieldNumber: 3)
    }
    if self.ringCapacity != 0 {
      try visitor.visitSingularUInt64Field(value: self.ringCapacity, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Ldtx_Recording_Xpc_V1_ConfigureRequest, rhs: Ldtx_Recording_Xpc_V1_ConfigureRequest) -> Bool {
    if lhs.protocolVersion != rhs.protocolVersion {return false}
    if lhs._context != rhs._context {return false}
    if lhs.trackID != rhs.trackID {return false}
    if lhs.ringCapacity != rhs.ringCapacity {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Ldtx_Recording_Xpc_V1_CutRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".CutRequest"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}context\0\u{3}cut_id\0\u{3}presentation_value\0\u{3}presentation_timescale\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._context) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.cutID) }()
      case 3: try { try decoder.decodeSingularInt64Field(value: &self.presentationValue) }()
      case 4: try { try decoder.decodeSingularInt32Field(value: &self.presentationTimescale) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._context {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    if !self.cutID.isEmpty {
      try visitor.visitSingularStringField(value: self.cutID, fieldNumber: 2)
    }
    if self.presentationValue != 0 {
      try visitor.visitSingularInt64Field(value: self.presentationValue, fieldNumber: 3)
    }
    if self.presentationTimescale != 0 {
      try visitor.visitSingularInt32Field(value: self.presentationTimescale, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Ldtx_Recording_Xpc_V1_CutRequest, rhs: Ldtx_Recording_Xpc_V1_CutRequest) -> Bool {
    if lhs._context != rhs._context {return false}
    if lhs.cutID != rhs.cutID {return false}
    if lhs.presentationValue != rhs.presentationValue {return false}
    if lhs.presentationTimescale != rhs.presentationTimescale {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Ldtx_Recording_Xpc_V1_FinishRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".FinishRequest"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}context\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._context) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._context {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Ldtx_Recording_Xpc_V1_FinishRequest, rhs: Ldtx_Recording_Xpc_V1_FinishRequest) -> Bool {
    if lhs._context != rhs._context {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Ldtx_Recording_Xpc_V1_Reply: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".Reply"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}accepted\0\u{3}error_message\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBoolField(value: &self.accepted) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.errorMessage) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.accepted != false {
      try visitor.visitSingularBoolField(value: self.accepted, fieldNumber: 1)
    }
    if !self.errorMessage.isEmpty {
      try visitor.visitSingularStringField(value: self.errorMessage, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Ldtx_Recording_Xpc_V1_Reply, rhs: Ldtx_Recording_Xpc_V1_Reply) -> Bool {
    if lhs.accepted != rhs.accepted {return false}
    if lhs.errorMessage != rhs.errorMessage {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Ldtx_Recording_Xpc_V1_Event: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".Event"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}context\0\u{1}kind\0\u{3}track_id\0\u{3}byte_offset\0\u{3}byte_length\0\u{3}presentation_value\0\u{3}presentation_timescale\0\u{3}duration_value\0\u{3}duration_timescale\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._context) }()
      case 2: try { try decoder.decodeSingularEnumField(value: &self.kind) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.trackID) }()
      case 4: try { try decoder.decodeSingularUInt64Field(value: &self.byteOffset) }()
      case 5: try { try decoder.decodeSingularUInt64Field(value: &self.byteLength) }()
      case 6: try { try decoder.decodeSingularInt64Field(value: &self.presentationValue) }()
      case 7: try { try decoder.decodeSingularInt32Field(value: &self.presentationTimescale) }()
      case 8: try { try decoder.decodeSingularInt64Field(value: &self.durationValue) }()
      case 9: try { try decoder.decodeSingularInt32Field(value: &self.durationTimescale) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._context {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    if self.kind != .unspecified {
      try visitor.visitSingularEnumField(value: self.kind, fieldNumber: 2)
    }
    if !self.trackID.isEmpty {
      try visitor.visitSingularStringField(value: self.trackID, fieldNumber: 3)
    }
    if self.byteOffset != 0 {
      try visitor.visitSingularUInt64Field(value: self.byteOffset, fieldNumber: 4)
    }
    if self.byteLength != 0 {
      try visitor.visitSingularUInt64Field(value: self.byteLength, fieldNumber: 5)
    }
    if self.presentationValue != 0 {
      try visitor.visitSingularInt64Field(value: self.presentationValue, fieldNumber: 6)
    }
    if self.presentationTimescale != 0 {
      try visitor.visitSingularInt32Field(value: self.presentationTimescale, fieldNumber: 7)
    }
    if self.durationValue != 0 {
      try visitor.visitSingularInt64Field(value: self.durationValue, fieldNumber: 8)
    }
    if self.durationTimescale != 0 {
      try visitor.visitSingularInt32Field(value: self.durationTimescale, fieldNumber: 9)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Ldtx_Recording_Xpc_V1_Event, rhs: Ldtx_Recording_Xpc_V1_Event) -> Bool {
    if lhs._context != rhs._context {return false}
    if lhs.kind != rhs.kind {return false}
    if lhs.trackID != rhs.trackID {return false}
    if lhs.byteOffset != rhs.byteOffset {return false}
    if lhs.byteLength != rhs.byteLength {return false}
    if lhs.presentationValue != rhs.presentationValue {return false}
    if lhs.presentationTimescale != rhs.presentationTimescale {return false}
    if lhs.durationValue != rhs.durationValue {return false}
    if lhs.durationTimescale != rhs.durationTimescale {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Ldtx_Recording_Xpc_V1_Event.Kind: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0KIND_UNSPECIFIED\0\u{1}KIND_PREPARED\0\u{1}KIND_FRAGMENT_COMMITTED\0\u{1}KIND_GENERATION_FINISHED\0\u{1}KIND_FAILED\0\u{1}KIND_RECOVERED\0")
}
