// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: persistence.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

// SPDX-FileCopyrightText: 2026 Kaito Udagawa <umireon@kaito.tokyo>
//
// SPDX-License-Identifier: Apache-2.0

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public nonisolated enum Ldtx_Program_Persistence_V1_InputDeviceKind: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case unspecified // = 0
  case video // = 1
  case audio // = 2
  case UNRECOGNIZED(Int)

  public init() {
    self = .unspecified
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .video
    case 2: self = .audio
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .video: return 1
    case .audio: return 2
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [Ldtx_Program_Persistence_V1_InputDeviceKind] = [
    .unspecified,
    .video,
    .audio,
  ]

}

public nonisolated enum Ldtx_Program_Persistence_V1_BackgroundRemovalPolicy: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case unspecified // = 0
  case enabled // = 1
  case disabled // = 2
  case UNRECOGNIZED(Int)

  public init() {
    self = .unspecified
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .enabled
    case 2: self = .disabled
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .enabled: return 1
    case .disabled: return 2
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [Ldtx_Program_Persistence_V1_BackgroundRemovalPolicy] = [
    .unspecified,
    .enabled,
    .disabled,
  ]

}

public nonisolated enum Ldtx_Program_Persistence_V1_ColorRangePolicy: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case unspecified // = 0
  case videoRange // = 1
  case fullRange // = 2
  case UNRECOGNIZED(Int)

  public init() {
    self = .unspecified
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .videoRange
    case 2: self = .fullRange
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .videoRange: return 1
    case .fullRange: return 2
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [Ldtx_Program_Persistence_V1_ColorRangePolicy] = [
    .unspecified,
    .videoRange,
    .fullRange,
  ]

}

public nonisolated struct Ldtx_Program_Persistence_V1_SavedProgramDefinitionLibrary: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var records: [Ldtx_Program_Persistence_V1_SavedProgramDefinitionRecord] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public nonisolated struct Ldtx_Program_Persistence_V1_SavedProgramDefinitionRecord: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var name: String = String()

  public var canvasWidth: UInt32 = 0

  public var canvasHeight: UInt32 = 0

  public var frameRateNumerator: UInt32 = 0

  public var frameRateDenominator: UInt32 = 0

  public var program: Ldtx_Program_V1_Program {
    get {_program ?? Ldtx_Program_V1_Program()}
    set {_program = newValue}
  }
  /// Returns true if `program` has been explicitly set.
  public var hasProgram: Bool {self._program != nil}
  /// Clears the value of `program`. Subsequent reads from it will return its default value.
  public mutating func clearProgram() {self._program = nil}

  public var inputDevices: [Ldtx_Program_Persistence_V1_InputDeviceRecord] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _program: Ldtx_Program_V1_Program? = nil
}

public nonisolated struct Ldtx_Program_Persistence_V1_ProgramPreferences: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var audioChannelGainsByName: Dictionary<String,Double> = [:]

  public var videoMutedByInputDeviceName: Dictionary<String,Bool> = [:]

  public var audioMutedByInputDeviceName: Dictionary<String,Bool> = [:]

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public nonisolated struct Ldtx_Program_Persistence_V1_InputDeviceRecord: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var name: String = String()

  public var kind: Ldtx_Program_Persistence_V1_InputDeviceKind = .unspecified

  public var physicalDeviceID: String = String()

  public var backgroundRemovalPolicy: Ldtx_Program_Persistence_V1_BackgroundRemovalPolicy = .unspecified

  public var colorRangePolicy: Ldtx_Program_Persistence_V1_ColorRangePolicy = .unspecified

  public var captureWidthOverride: UInt32 = 0

  public var captureHeightOverride: UInt32 = 0

  public var captureFrameRateOverride: UInt32 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "ldtx.program.persistence.v1"

nonisolated extension Ldtx_Program_Persistence_V1_InputDeviceKind: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0INPUT_DEVICE_KIND_UNSPECIFIED\0\u{1}INPUT_DEVICE_KIND_VIDEO\0\u{1}INPUT_DEVICE_KIND_AUDIO\0")
}

nonisolated extension Ldtx_Program_Persistence_V1_BackgroundRemovalPolicy: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0BACKGROUND_REMOVAL_POLICY_UNSPECIFIED\0\u{1}BACKGROUND_REMOVAL_POLICY_ENABLED\0\u{1}BACKGROUND_REMOVAL_POLICY_DISABLED\0")
}

nonisolated extension Ldtx_Program_Persistence_V1_ColorRangePolicy: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0COLOR_RANGE_POLICY_UNSPECIFIED\0\u{1}COLOR_RANGE_POLICY_VIDEO_RANGE\0\u{1}COLOR_RANGE_POLICY_FULL_RANGE\0")
}

nonisolated extension Ldtx_Program_Persistence_V1_SavedProgramDefinitionLibrary: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".SavedProgramDefinitionLibrary"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}records\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.records) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.records.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.records, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Ldtx_Program_Persistence_V1_SavedProgramDefinitionLibrary, rhs: Ldtx_Program_Persistence_V1_SavedProgramDefinitionLibrary) -> Bool {
    if lhs.records != rhs.records {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Ldtx_Program_Persistence_V1_SavedProgramDefinitionRecord: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".SavedProgramDefinitionRecord"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}name\0\u{3}canvas_width\0\u{3}canvas_height\0\u{3}frame_rate_numerator\0\u{3}frame_rate_denominator\0\u{1}program\0\u{3}input_devices\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.name) }()
      case 2: try { try decoder.decodeSingularUInt32Field(value: &self.canvasWidth) }()
      case 3: try { try decoder.decodeSingularUInt32Field(value: &self.canvasHeight) }()
      case 4: try { try decoder.decodeSingularUInt32Field(value: &self.frameRateNumerator) }()
      case 5: try { try decoder.decodeSingularUInt32Field(value: &self.frameRateDenominator) }()
      case 6: try { try decoder.decodeSingularMessageField(value: &self._program) }()
      case 7: try { try decoder.decodeRepeatedMessageField(value: &self.inputDevices) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 1)
    }
    if self.canvasWidth != 0 {
      try visitor.visitSingularUInt32Field(value: self.canvasWidth, fieldNumber: 2)
    }
    if self.canvasHeight != 0 {
      try visitor.visitSingularUInt32Field(value: self.canvasHeight, fieldNumber: 3)
    }
    if self.frameRateNumerator != 0 {
      try visitor.visitSingularUInt32Field(value: self.frameRateNumerator, fieldNumber: 4)
    }
    if self.frameRateDenominator != 0 {
      try visitor.visitSingularUInt32Field(value: self.frameRateDenominator, fieldNumber: 5)
    }
    try { if let v = self._program {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 6)
    } }()
    if !self.inputDevices.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.inputDevices, fieldNumber: 7)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Ldtx_Program_Persistence_V1_SavedProgramDefinitionRecord, rhs: Ldtx_Program_Persistence_V1_SavedProgramDefinitionRecord) -> Bool {
    if lhs.name != rhs.name {return false}
    if lhs.canvasWidth != rhs.canvasWidth {return false}
    if lhs.canvasHeight != rhs.canvasHeight {return false}
    if lhs.frameRateNumerator != rhs.frameRateNumerator {return false}
    if lhs.frameRateDenominator != rhs.frameRateDenominator {return false}
    if lhs._program != rhs._program {return false}
    if lhs.inputDevices != rhs.inputDevices {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Ldtx_Program_Persistence_V1_ProgramPreferences: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ProgramPreferences"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}audio_channel_gains_by_name\0\u{3}video_muted_by_input_device_name\0\u{3}audio_muted_by_input_device_name\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufDouble>.self, value: &self.audioChannelGainsByName) }()
      case 2: try { try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufBool>.self, value: &self.videoMutedByInputDeviceName) }()
      case 3: try { try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufBool>.self, value: &self.audioMutedByInputDeviceName) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.audioChannelGainsByName.isEmpty {
      try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufDouble>.self, value: self.audioChannelGainsByName, fieldNumber: 1)
    }
    if !self.videoMutedByInputDeviceName.isEmpty {
      try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufBool>.self, value: self.videoMutedByInputDeviceName, fieldNumber: 2)
    }
    if !self.audioMutedByInputDeviceName.isEmpty {
      try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufBool>.self, value: self.audioMutedByInputDeviceName, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Ldtx_Program_Persistence_V1_ProgramPreferences, rhs: Ldtx_Program_Persistence_V1_ProgramPreferences) -> Bool {
    if lhs.audioChannelGainsByName != rhs.audioChannelGainsByName {return false}
    if lhs.videoMutedByInputDeviceName != rhs.videoMutedByInputDeviceName {return false}
    if lhs.audioMutedByInputDeviceName != rhs.audioMutedByInputDeviceName {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Ldtx_Program_Persistence_V1_InputDeviceRecord: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".InputDeviceRecord"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}name\0\u{1}kind\0\u{4}\u{3}physical_device_id\0\u{3}background_removal_policy\0\u{3}color_range_policy\0\u{3}capture_width_override\0\u{3}capture_height_override\0\u{3}capture_frame_rate_override\0\u{b}side_track_recording_policy\0\u{b}id\0\u{c}\u{3}\u{1}\u{c}\u{4}\u{1}")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.name) }()
      case 2: try { try decoder.decodeSingularEnumField(value: &self.kind) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self.physicalDeviceID) }()
      case 6: try { try decoder.decodeSingularEnumField(value: &self.backgroundRemovalPolicy) }()
      case 7: try { try decoder.decodeSingularEnumField(value: &self.colorRangePolicy) }()
      case 8: try { try decoder.decodeSingularUInt32Field(value: &self.captureWidthOverride) }()
      case 9: try { try decoder.decodeSingularUInt32Field(value: &self.captureHeightOverride) }()
      case 10: try { try decoder.decodeSingularUInt32Field(value: &self.captureFrameRateOverride) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 1)
    }
    if self.kind != .unspecified {
      try visitor.visitSingularEnumField(value: self.kind, fieldNumber: 2)
    }
    if !self.physicalDeviceID.isEmpty {
      try visitor.visitSingularStringField(value: self.physicalDeviceID, fieldNumber: 5)
    }
    if self.backgroundRemovalPolicy != .unspecified {
      try visitor.visitSingularEnumField(value: self.backgroundRemovalPolicy, fieldNumber: 6)
    }
    if self.colorRangePolicy != .unspecified {
      try visitor.visitSingularEnumField(value: self.colorRangePolicy, fieldNumber: 7)
    }
    if self.captureWidthOverride != 0 {
      try visitor.visitSingularUInt32Field(value: self.captureWidthOverride, fieldNumber: 8)
    }
    if self.captureHeightOverride != 0 {
      try visitor.visitSingularUInt32Field(value: self.captureHeightOverride, fieldNumber: 9)
    }
    if self.captureFrameRateOverride != 0 {
      try visitor.visitSingularUInt32Field(value: self.captureFrameRateOverride, fieldNumber: 10)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Ldtx_Program_Persistence_V1_InputDeviceRecord, rhs: Ldtx_Program_Persistence_V1_InputDeviceRecord) -> Bool {
    if lhs.name != rhs.name {return false}
    if lhs.kind != rhs.kind {return false}
    if lhs.physicalDeviceID != rhs.physicalDeviceID {return false}
    if lhs.backgroundRemovalPolicy != rhs.backgroundRemovalPolicy {return false}
    if lhs.colorRangePolicy != rhs.colorRangePolicy {return false}
    if lhs.captureWidthOverride != rhs.captureWidthOverride {return false}
    if lhs.captureHeightOverride != rhs.captureHeightOverride {return false}
    if lhs.captureFrameRateOverride != rhs.captureFrameRateOverride {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
