// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: persistence.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

// SPDX-FileCopyrightText: 2026 Kaito Udagawa <umireon@kaito.tokyo>
//
// SPDX-License-Identifier: Apache-2.0

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public nonisolated struct Ldtx_Program_Persistence_V1_SavedProgramDefinitionLibrary: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var records: [Ldtx_Program_Persistence_V1_SavedProgramDefinitionRecord] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public nonisolated struct Ldtx_Program_Persistence_V1_SavedProgramDefinitionRecord: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var name: String = String()

  public var canvasWidth: UInt32 = 0

  public var canvasHeight: UInt32 = 0

  public var frameRateNumerator: UInt32 = 0

  public var frameRateDenominator: UInt32 = 0

  public var program: Ldtx_Program_V1_Program {
    get {_program ?? Ldtx_Program_V1_Program()}
    set {_program = newValue}
  }
  /// Returns true if `program` has been explicitly set.
  public var hasProgram: Bool {self._program != nil}
  /// Clears the value of `program`. Subsequent reads from it will return its default value.
  public mutating func clearProgram() {self._program = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _program: Ldtx_Program_V1_Program? = nil
}

public nonisolated struct Ldtx_Program_Persistence_V1_SavedProgramArgumentsLibrary: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var records: [Ldtx_Program_Persistence_V1_SavedProgramArgumentsRecord] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public nonisolated struct Ldtx_Program_Persistence_V1_SavedProgramArgumentsRecord: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var name: String = String()

  public var arguments: Ldtx_Program_Persistence_V1_ProgramArguments {
    get {_arguments ?? Ldtx_Program_Persistence_V1_ProgramArguments()}
    set {_arguments = newValue}
  }
  /// Returns true if `arguments` has been explicitly set.
  public var hasArguments: Bool {self._arguments != nil}
  /// Clears the value of `arguments`. Subsequent reads from it will return its default value.
  public mutating func clearArguments() {self._arguments = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _arguments: Ldtx_Program_Persistence_V1_ProgramArguments? = nil
}

public nonisolated struct Ldtx_Program_Persistence_V1_ProgramArguments: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var audioChannelGainsByName: Dictionary<String,Double> = [:]

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "ldtx.program.persistence.v1"

nonisolated extension Ldtx_Program_Persistence_V1_SavedProgramDefinitionLibrary: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".SavedProgramDefinitionLibrary"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}records\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.records) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.records.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.records, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Ldtx_Program_Persistence_V1_SavedProgramDefinitionLibrary, rhs: Ldtx_Program_Persistence_V1_SavedProgramDefinitionLibrary) -> Bool {
    if lhs.records != rhs.records {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Ldtx_Program_Persistence_V1_SavedProgramDefinitionRecord: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".SavedProgramDefinitionRecord"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}name\0\u{3}canvas_width\0\u{3}canvas_height\0\u{3}frame_rate_numerator\0\u{3}frame_rate_denominator\0\u{1}program\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.name) }()
      case 2: try { try decoder.decodeSingularUInt32Field(value: &self.canvasWidth) }()
      case 3: try { try decoder.decodeSingularUInt32Field(value: &self.canvasHeight) }()
      case 4: try { try decoder.decodeSingularUInt32Field(value: &self.frameRateNumerator) }()
      case 5: try { try decoder.decodeSingularUInt32Field(value: &self.frameRateDenominator) }()
      case 6: try { try decoder.decodeSingularMessageField(value: &self._program) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 1)
    }
    if self.canvasWidth != 0 {
      try visitor.visitSingularUInt32Field(value: self.canvasWidth, fieldNumber: 2)
    }
    if self.canvasHeight != 0 {
      try visitor.visitSingularUInt32Field(value: self.canvasHeight, fieldNumber: 3)
    }
    if self.frameRateNumerator != 0 {
      try visitor.visitSingularUInt32Field(value: self.frameRateNumerator, fieldNumber: 4)
    }
    if self.frameRateDenominator != 0 {
      try visitor.visitSingularUInt32Field(value: self.frameRateDenominator, fieldNumber: 5)
    }
    try { if let v = self._program {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 6)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Ldtx_Program_Persistence_V1_SavedProgramDefinitionRecord, rhs: Ldtx_Program_Persistence_V1_SavedProgramDefinitionRecord) -> Bool {
    if lhs.name != rhs.name {return false}
    if lhs.canvasWidth != rhs.canvasWidth {return false}
    if lhs.canvasHeight != rhs.canvasHeight {return false}
    if lhs.frameRateNumerator != rhs.frameRateNumerator {return false}
    if lhs.frameRateDenominator != rhs.frameRateDenominator {return false}
    if lhs._program != rhs._program {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Ldtx_Program_Persistence_V1_SavedProgramArgumentsLibrary: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".SavedProgramArgumentsLibrary"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}records\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.records) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.records.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.records, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Ldtx_Program_Persistence_V1_SavedProgramArgumentsLibrary, rhs: Ldtx_Program_Persistence_V1_SavedProgramArgumentsLibrary) -> Bool {
    if lhs.records != rhs.records {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Ldtx_Program_Persistence_V1_SavedProgramArgumentsRecord: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".SavedProgramArgumentsRecord"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}name\0\u{1}arguments\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.name) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._arguments) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 1)
    }
    try { if let v = self._arguments {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Ldtx_Program_Persistence_V1_SavedProgramArgumentsRecord, rhs: Ldtx_Program_Persistence_V1_SavedProgramArgumentsRecord) -> Bool {
    if lhs.name != rhs.name {return false}
    if lhs._arguments != rhs._arguments {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Ldtx_Program_Persistence_V1_ProgramArguments: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ProgramArguments"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}audio_channel_gains_by_name\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufDouble>.self, value: &self.audioChannelGainsByName) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.audioChannelGainsByName.isEmpty {
      try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufDouble>.self, value: self.audioChannelGainsByName, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Ldtx_Program_Persistence_V1_ProgramArguments, rhs: Ldtx_Program_Persistence_V1_ProgramArguments) -> Bool {
    if lhs.audioChannelGainsByName != rhs.audioChannelGainsByName {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
