// SPDX-FileCopyrightText: 2026 Kaito Udagawa <umireon@kaito.tokyo>
//
// SPDX-License-Identifier: Apache-2.0

import Foundation

/// Identifies the concrete kinds of additional data generated by LDTX.
public enum BackgroundTaskKey: Hashable, Sendable {
  case vision(String)
  case automation(String)
}

/// Describes why LDTX submitted a background generation task.
public enum BackgroundTaskSubmission: Equatable, Sendable {
  case manual
  case periodic
  case postAction
}

/// A fire-and-forget queue for serial access to shared generated-data state.
///
/// Tasks communicate through their shared workspace storage, not through this
/// queue. The completion closure only marks execution as finished and carries
/// no result. Stopping is cooperative and makes the queue permanently unusable.
public final class BackgroundTaskQueue: @unchecked Sendable {
  public typealias Completion = @Sendable () -> Void
  public typealias Task = @Sendable (_ stopToken: StopToken) -> Void
  public typealias TaskFactory = @Sendable (_ completion: @escaping Completion) -> Task

  private enum State {
    case accepting
    case stopping
    case stopped
  }

  private struct Entry: Sendable {
    var id: UUID
    var key: BackgroundTaskKey
    var task: Task
  }

  public let stopToken = StopToken()

  private let controlQueue: DispatchQueue
  private let executionQueue: DispatchQueue
  private var state = State.accepting
  private var pending: [Entry] = []
  private var running: Entry?
  private var stopHandlers: [@MainActor @Sendable () -> Void] = []

  public init(label: String) {
    controlQueue = DispatchQueue(label: label)
    executionQueue = DispatchQueue(label: "\(label).execution")
  }

  /// Fire-and-forget submission. The task receives no result channel; captured
  /// workspace storage is the only intended data exchange mechanism.
  @discardableResult
  public func submit(
    key: BackgroundTaskKey,
    source: BackgroundTaskSubmission,
    _ factory: TaskFactory
  ) -> Bool {
    controlQueue.sync {
      guard state == .accepting else { return false }
      switch source {
      case .manual, .postAction:
        guard running?.key != key, !pending.contains(where: { $0.key == key }) else {
          return false
        }
      case .periodic:
        guard running == nil, pending.isEmpty else { return false }
      }

      let id = UUID()
      let completion = OneShotCompletion { [weak self] in
        self?.controlQueue.async { [weak self] in self?.finish(id: id) }
      }
      pending.append(Entry(id: id, key: key, task: factory(completion.callAsFunction)))
      startNextIfNeeded()
      return true
    }
  }

  /// Permanently stops this queue. Pending work is discarded and the running
  /// task is asked to stop cooperatively. The notification is delivered once
  /// on MainActor after that task reports completion.
  public func stop(
    completionHandler: @escaping @MainActor @Sendable () -> Void = {}
  ) {
    controlQueue.async { [self] in
      switch state {
      case .accepting:
        state = .stopping
        stopToken.requestStop()
        pending.removeAll()
        stopHandlers.append(completionHandler)
        completeStopIfPossible()
      case .stopping:
        stopHandlers.append(completionHandler)
      case .stopped:
        notifyOnMainActor(completionHandler)
      }
    }
  }

  private func startNextIfNeeded() {
    guard state == .accepting, running == nil else {
      completeStopIfPossible()
      return
    }
    guard !pending.isEmpty else { return }
    let entry = pending.removeFirst()
    running = entry
    executionQueue.async { [stopToken] in entry.task(stopToken) }
  }

  private func finish(id: UUID) {
    guard running?.id == id else { return }
    running = nil
    if state == .accepting {
      startNextIfNeeded()
    } else {
      pending.removeAll()
      completeStopIfPossible()
    }
  }

  private func completeStopIfPossible() {
    guard state == .stopping, running == nil else { return }
    state = .stopped
    let handlers = stopHandlers
    stopHandlers.removeAll()
    handlers.forEach(notifyOnMainActor)
  }

  private func notifyOnMainActor(_ handler: @escaping @MainActor @Sendable () -> Void) {
    DispatchQueue.main.async {
      MainActor.assumeIsolated { handler() }
    }
  }
}
