# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

# SPDX-FileCopyrightText: 2026 Kaito Udagawa <umireon@kaito.tokyo>
#
# SPDX-License-Identifier: Apache-2.0

name: Check CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions: {}

jobs:
  check-clang-format:
    runs-on: ubuntu-26.04-arm
    timeout-minutes: 10

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Print clang-format version
        shell: bash --noprofile --norc -euo pipefail -O nullglob {0}
        run: |
          clang-format --version

      - name: Check with clang-format
        shell: bash --noprofile --norc -euo pipefail -O nullglob {0}
        run: |
          git ls-files '*.cpp' '*.hpp' | xargs --no-run-if-empty clang-format --dry-run --Werror

  check-swift-format:
    runs-on: macos-26
    timeout-minutes: 10

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Print swift-format version
        shell: bash --noprofile --norc -euo pipefail -O nullglob {0}
        run: |
          swift format --version

      - name: Check with clang-format
        shell: bash --noprofile --norc -euo pipefail -O nullglob {0}
        run: |
          swift format lint --recursive .

  check-reuse:
    runs-on: ubuntu-26.04-arm
    timeout-minutes: 10

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Install reuse with pipx
        shell: bash --noprofile --norc -euo pipefail -O nullglob {0}
        run: |
          pipx install reuse
          printf '%s/.local/bin\n' "$HOME" >> "$GITHUB_PATH"

      - name: Check with reuse
        shell: bash --noprofile --norc -euo pipefail -O nullglob {0}
        run: |
          reuse lint

  accept-check:
    if: always()
    needs:
      - check-clang-format
      - check-swift-format
      - check-reuse
    runs-on: ubuntu-slim
    permissions: {}
    steps:
      - name: Check workflow results
        shell: bash --noprofile --norc -euo pipefail -O nullglob {0}
        run: |
          [[ '${{ needs.check-clang-format.result }}' == 'success' ]] &&
          [[ '${{ needs.check-swift-format.result }}' == 'success' ]] &&
          [[ '${{ needs.check-reuse.result }}' == 'success' ]] &&
          printf 'OK\n'
