# This workflow is managed by gh actions-lock.
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

# SPDX-FileCopyrightText: 2026 Kaito Udagawa <umireon@kaito.tokyo>
#
# SPDX-License-Identifier: Apache-2.0

name: PR Check

on:
  pull_request:

concurrency:
  group: pr-check-${{ github.ref }}
  cancel-in-progress: true

jobs:
  actions:
    uses: ./.github/workflows/actions.yml
    permissions:
      contents: read

  docs-build:
    runs-on: ubuntu-26.04
    timeout-minutes: 10

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.1

      - name: Setup Pages
        uses: actions/configure-pages@v6.0.0

      - name: Build
        shell: bash --noprofile --norc -euo pipefail -O nullglob {0}
        working-directory: docs
        run: node _BUILD.mjs dist

  tools:
    uses: ./.github/workflows/tools.yml
    permissions:
      contents: read

  xcode:
    uses: ./.github/workflows/xcode.yml
    permissions:
      contents: read

  accept-pr-check:
    if: always()
    needs:
      - actions
      - docs-build
      - tools
      - xcode
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    permissions: {}
    steps:
      - name: Check workflow results
        env:
          NEEDS: ${{ toJSON(needs) }}
        shell: bash --noprofile --norc -euo pipefail -O nullglob {0}
        run: jq -e 'all(.[]; .result == "success")' <<< "${NEEDS:?}"
